(function(z){
'use strict';var D7=function(a){z.L.call(this);this.aa(a)},E7=function(a){z.L.call(this);this.aa(a)},x6a=function(a,b){this.user=a;this.quotes=b},y6a=function(a,b){b=b.g();if(b===Number||b.$isProtoEnum)return a=Number(a),Number.isNaN(a)?void 0:a;if(b===Boolean)return!!a;if(b===String)return String(a)},F7=function(a){return a.ZB.best||null},G7=function(a,b){b=b.filter(function(a){return"anon"!=a.mb()});b=z.bb(b,function(a){return a.mb()},a);return z.gb(b).map(function(a){return new x6a(a[0].hc(),a)},
a)},z6a=function(a,b,c,d){return(0,z.Kc)(a.gu[b.name]||[],function(a){return a.Gd()==c&&a.Ce()==d})},H7=function(){this.LH=1},I7=function(a){z.uh.call(this);this.aa(a)},A6a=function(a,b){return z.K(a,"slots",b)},B6a=function(a,b){return z.K(a,"requestContext",b)},J7=function(a){z.L.call(this);this.aa(a)},K7=function(a){return z.J(a,"inResponseToMediaResource")},L7=function(a){return z.J(a,"mediumQuote")},C6a=function(a,b){a.aR=b;return a},M7=function(a,b){return F7(a)?z.QC(F7(a)).filter(function(a){return this.j6(a)==
b},a):[]},D6a=function(a){a=new Date(a);return Date.UTC(a.getFullYear(),a.getMonth()+1,1)-1},E6a=function(a){var b=z.QM(a.qk.Gt,a.qk.Zr(),a.xm.Gt,a.xm.Zr()).Ia().trim();0<a.qk.Zr()&&(b="…"+b);var c=z.BD(a.Cc,a.xm.Gt);a.xm.Zr()<c.Ia().length&&(b+="…");return b},F6a=function(a){var b=z.tB(a.vAa),c=a.qk.Gt,d=c?b.indexOf(c):-1,e=(c=a.xm.Gt)?b.indexOf(c):-1;if(-1==d||-1==e)return"";for(c=[];d<=e;d++)c.push(z.BD(a.Cc,b[d]));b=z.Ma(c);a=z.vt(c.indexOf(c[0]),a.qk.Zr(),c.indexOf(b),a.xm.Zr(),!1);return z.pka(new z.it(z.Gl,
z.kEa),c,a,!0)},G6a=function(a,b,c){c=c.Ay;b=b.getAttribute("name").split(" ");var d=z.qb(b);a=(a.gu[c.name]||[]).filter(function(a){return d[a.ej()]});return a.length?z.hwa(a):null},H6a=function(a,b,c,d){b=z6a(a,b,c,d);return G7(a,b)},I6a=function(a,b){var c=0;(a.gu[b]||[]).forEach(function(a){"anon"==a.mb()&&(c+=a.Me())});return c},J6a=function(a,b,c){var d=a.ma.la(z.TDa,{postId:b},{filter:c});return z.nD(a,d,function(){return this.Eb.Ul(d)})},K6a=function(a,b){return z.sa(b)in a.JA},L6a=function(a,
b){z.Rs(a,7);var c=new z.Is("",1,a.Ia());b.forEach(function(a){z.Ps(c,z.zs(a.startOffset,a.endOffset,[a.quoteId],[a.userId]))},a);b=z.cka(c);for(var d=z.dka(c,b),e=0;e<b.length;e++){var g=d[e];if(g.length){for(var k={},l=[],p=0;p<g.length;p++){var r=g[p];k[z.J(r,"creatorIds")]=!0;l.push(r.getName())}g=b[e];p=e<b.length-1?b[e+1]:a.Ia().length;z.Ps(a,z.zs(g,p,l,Object.keys(k)))}}},M6a=function(a,b){var c=a.text,d=a.l,e="";a=""+z.A(z.Ch(a));a=(0,z.N)(a);e+=z.A(z.O({s:c,ac:!0,Ze:!0,href:(0,z.M)(""+z.G(b.tq)),
source:a,style:"link.obvious",wa:!0,l:d},b));return(0,z.y)(e)},N6a=function(a,b,c){b="";a.fIa?a=z.n("Top highlight"):(c=""+z.A(z.jP(z.D({o7:!0,Hma:!c.useragent.isMobile},a),c)),1==a.Ki&&a.isActive&&(a=z.n("highlighted"),c+=" "+a),a=(0,z.y)(c));b+=a;return(0,z.y)(b)},N7=function(a,b){this.ti=a;this.gua=b;this.Re=(this.Yk=b=z.oB(a.node,b))&&b.getAttribute("name");this.PQ=b?z.mw(a,b):-1},O7=function(a){var b=a.length;a=a.match(O6a);if(!a)return b;for(var c=0;c<a.length;c++)b+=23-a[c].length;return b},
P6a=function(a,b,c){return(0,z.y)(z.TO(z.D({user:c.currentUser,type:"quoteResponses"},a),c))},Q6a=function(a,b,c){return(0,z.y)(z.A(z.vj({icon:(0,z.N)(""+z.A(z.Zi())),wa:!0,action:"dismiss-meter",l:"js-dismissMeterButton"},c)))},R6a=function(a){var b,c="";switch(z.qa(b=a.meteringInfo.postIds.length)?b.toString():b){case 0:case 1:a=z.n("Your first three are on the house.");c+=a;break;case 2:a=z.n("That’s two for you...");c+=a;break;default:a=z.n("We like your style."),c+=a}return(0,z.y)(c)},P7=function(a){z.L.call(this);
this.aa(a)},S6a=function(a,b,c){b="\x3cdiv class\x3d'u-marginLeft10'\x3e\x3cdiv class\x3d\"buttonSet u-inlineBlock\"\x3e"+z.A(z.vj({action:"quote",source:"quote_popover",icon:(0,z.N)(""+z.A(z.fea())),l:(0,z.N)("button--highlightMenu u-sm-height42 u-sm-lineHeight44 u-accentColor--highlightStrong js-quoteAttributions-pileOn"),ac:!0,Xj:!0,aT:"quote",wa:!0,isActive:a.isActive},c))+(c.supportsEdit?z.A(z.vj({action:"quote-respond",source:"quote_popover",icon:(0,z.N)(""+z.A(z.kea())),l:"button--highlightMenu u-sm-height42 u-sm-lineHeight44",
ac:!0,wa:!0},c)):"")+(a.HW?z.A(z.vj({action:"twitter",source:"quote_popover",icon:(0,z.N)(""+z.A(z.ej(null))),l:"button--highlightMenu u-sm-height42 u-sm-lineHeight44",ac:!0,wa:!0},c)):"")+'\x3cdiv class\x3d"buttonSet-separator"\x3e\x3c/div\x3e\x3c/div\x3e';b+='\x3cdiv class\x3d"'+z.F(z.E("js-quoteAttributions-info u-inlineBlock u-verticalAlignTop u-noWrapWithEllipsis u-maxWidth414 u-paddingTop11 u-paddingRight18 u-paddingBottom0 u-paddingLeft10 u-xs-paddingTop13 u-xs-paddingLeft4 u-xs-maxWidth160"))+
'"\x3e'+N6a(a,0,c)+"\x3c/div\x3e\x3c/div\x3e";return(0,z.y)(b)},Q7=function(a){z.Il.call(this);var b=z.$m();this.qk=b&&new N7(z.Cn(b,!0),a);this.xm=b&&new N7(z.Cn(b,!1),a)},R7=function(a,b){var c=new z.Dh(z.Fl(b)),c=new z.td(c.la(z.VCa)),d=new z.td("https://www.facebook.com/v2.7/dialog/share");z.Ad(d,z.Md({app_id:b.facebook.key,href:a.toString(),display:"popup",redirect_uri:c.toString()}));return d},T6a=function(a,b,c){function d(a){return a.replace(/“/g,"‘").replace(/”/g,"’").replace(/„/g,"‚").replace(/'/g,
"’")}b.content=d(b.content);b.name&&(b.name=d(b.name));var e=String(a(b,null,c)),g=O7(e)-280;0<g&&(b.content=z.bh(b.content,b.content.length-g),e=String(a(b,null,c)));return e},U6a=function(a,b){b=new z.Dh(b.authBaseUrl);return new z.td(b.Fl(a))},V6a=function(){var a=z.n("Highlights");return(0,z.y)(""+a)},W6a=function(a,b,c){b=a.post.virtuals.responsesCreatedCount>=c.j.J8&&(a.post.creator.userId==c.currentUser.userId||(null==a.post.homeCollection?null:null==a.post.homeCollection.virtuals?null:null==
a.post.homeCollection.virtuals.permissions?null:a.post.homeCollection.virtuals.permissions.canManageAll));var d=z.D({G9:b},a),d=d||{},d=d.G9;a=""+('\x3cdiv class\x3d"container u-maxWidth740"\x3e\x3cdiv class\x3d"responsesStreamWrapper u-maxWidth640 u-hide js-responsesStreamWrapper"\x3e'+(0,z.y)('\x3cdiv class\x3d"container responsesStream-title u-paddingTop15"\x3e\x3cdiv class\x3d"row"\x3e'+z.A(z.wO({title:(0,z.N)(""+z.A(z.jk())),LD:!0,Wg:(0,z.N)(""+(c.supportsEdit&&d?z.JNa(null,c):""))},c))+"\x3c/div\x3e\x3c/div\x3e")+
z.HNa(z.D({te:b},a),c)+(b?z.INa(a,c):"")+z.GNa(c)+"\x3c/div\x3e\x3c/div\x3e");return(0,z.y)(a)},X6a=function(a,b,c){var d=a.l;b="";var e=c.useragent.isMobile&&!c.useragent.isTablet||1<(null==a.meteringInfo.postIds?null:a.meteringInfo.postIds.length),g;g=(0,z.N)(""+(e?"u-bottom15 u-sm-bottom10":"u-backgroundWhite u-boxShadowTop u-borderBottomLightest u-bottom0"));var k;k=(0,z.N)(""+(e?"u-backgroundWhite u-borderLightest u-boxShadow2px10pxBlackLighter u-borderRadius4":""));d='\x3cdiv class\x3d"postMeterBar u-sizeFullWidth u-fixed '+
z.F(g)+(d?" "+z.F(d):"")+' js-meterBanner" role\x3d"alert" aria-live\x3d"assertive"\x3e\x3cdiv class\x3d"u-borderBox u-maxWidth1040 u-marginAuto u-paddingTop25 u-paddingBottom25 u-paddingLeft20 u-paddingRight20 '+(e?z.F(k):"")+' u-sm-maxWidth740 u-xs-marginLeft10 u-xs-marginRight10 u-xs-paddingTop15 u-xs-paddingBottom15 u-xs-paddingLeft10 u-xs-paddingRight10"\x3e\x3cdiv class\x3d"u-flexCenter"\x3e\x3cdiv class\x3d"u-flex0 u-flexCenter"\x3e'+z.oF(a,c)+'\x3c/div\x3e\x3cdiv class\x3d"u-flex1 u-marginLeft20 u-marginTop8 u-xs-marginLeft10 u-xs-marginTop0"\x3e\x3cdiv class\x3d"'+
z.F(z.cl({sb:"regular"}))+' u-xs-hide"\x3e\x3cdiv class\x3d"ui-brand2"\x3e'+R6a(a)+'\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"'+z.F(z.cl({sb:"small"}))+' u-xs-show"\x3e\x3cdiv class\x3d"ui-h4"\x3e'+R6a(a)+'\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"u-flex0 u-marginLeft20 u-xs-marginLeft10 js-expandMeterButton"\x3e';g="";k=""+z.A(z.LO(null));k=(0,z.N)(k);if(c.useragent.isMobile)g+=z.A(z.vj({icon:k,wa:!0,action:"expand-meter"},c));else{var l=z.n("Details");g+=z.A(z.vj({text:(0,z.N)(""+l),
Nd:!0,icon:k,wa:!0,action:"expand-meter"},c))}g=(0,z.y)(g);var e=d+g+'\x3c/div\x3e\x3cdiv class\x3d"u-flex0 u-marginLeft40 u-flexCenter u-textColorNormal u-xs-marginLeft10 u-xs-hide js-dismissMeterIndicator"\x3e'+(e?(0,z.y)('\x3cfigure class\x3d"circleCountdown"\x3e\x3csvg role\x3d"img" xmlns\x3d"http://www.w3.org/2000/svg"\x3e\x3ccircle class\x3d"circleCountdown-fill" cx\x3d"50%" cy\x3d"50%" r\x3d"8px" /\x3e\x3c/svg\x3e\x3c/figure\x3e'):Q6a(0,0,c))+'\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"postMeterBar-details u-marginLeft137 u-paddingLeft20 u-paddingRight20 '+
z.F(z.cl({sb:"regular"}))+' u-sm-marginLeft137 u-xs-margin0 u-xs-padding0 js-moreInfo"\x3e\x3cp class\x3d"ui-body u-marginVertical10 u-xs-paddingTop10 u-xs-borderTopLight"\x3e',p,d="";g=a.post.lockedPostSource==c.j.Yv.bA;if(c.useragent.isMobile)if(g)switch(z.qa(p=a.meteringInfo.postIds.length)?p.toString():p){case 0:case 1:p=z.n("Enjoy daily, ad-free selections from The New York Times, The Atlantic, Fast Company, and more for $5/month.");d+=p;break;default:p=z.n("Access dozens of ad-free selections daily from the world’s leading publications for $5/month."),
d+=p}else switch(z.qa(p=a.meteringInfo.postIds.length)?p.toString():p){case 0:case 1:p=z.n("You can read three exclusive stories per month for free. Upgrade for unlimited access");d+=p;c.isAuthenticated||(p=z.n("sign in"),g=z.n(" or "),d+=g+M6a({text:(0,z.N)(""+p),susiEntry:c.j.Ha.Laa},c));d+=".";break;case 2:p=z.n("You’ve read two of your three free exclusive stories this month.");d+=p;break;default:p=z.n("This is your last free exclusive story for this month. Upgrade for unlimited access."),d+=
p}else if(g)switch(z.qa(p=a.meteringInfo.postIds.length)?p.toString():p){case 0:case 1:p=z.n("Enjoy daily, ad-free selections from The New York Times, The Atlantic, Fast Company, and more, when you upgrade for $5/month.");d+=p;break;default:p=z.n("Unlock the best of {$productName} when you upgrade for $5/month. Access dozens of ad-free selections daily from the world’s leading publications.",{productName:z.A(c.productName)}),d+=p}else switch(z.qa(p=a.meteringInfo.postIds.length)?p.toString():p){case 0:case 1:p=
z.n("Members get exclusive access to the best stories on {$productName} — but you can read three for free each month. Upgrade for $5/month for unlimited access.",{productName:z.A(c.productName)});d+=p;c.isAuthenticated||(p=z.n("Already a member?"),d+='\x3cspan class\x3d"u-block u-marginTop20"\x3e'+p+" "+M6a({text:(0,z.N)("Sign in"),susiEntry:c.j.Ha.Laa},c)+".\x3c/span\x3e");break;default:p=z.n("Unlock the best of {$productName} when you upgrade for $5/month. Access in-depth, insightful stories from top writers and publications.",
{productName:z.A(c.productName)}),d+=p}d=(0,z.y)(d);b+=e+d+'\x3c/p\x3e\x3cdiv class\x3d"u-marginTop20 u-xs-marginTop15"\x3e'+z.A(z.Vy({location:c.j.Jd.Jaa,lb:!0,Ba:!0,Bd:!0,Eh:!0,postId:a.post.id,collectionId:a.post.homeCollectionId,authorId:a.post.creatorId,l:"u-xs-sizeFullWidth"},c))+"\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e";return(0,z.y)(b)},S7=function(a,b,c){z.T.call(this);this.ze=a.get("quotes-data");var d=this.ze.xp;d.subscribe("add",this.Jfa,this);d.subscribe("remove",this.Jfa,this);
this.$a=b;this.we=b.sm;this.Cm=c;this.hca=[];this.Ja=a.get("app");this.Ga=a.get("popover");this.ma=a.get("route-builder");this.V_=a.get("global-event-bus");this.IAa=a.get("progressive-media-loader")},Z6a=function(a,b,c,d){var e=Y6a(a,b);if(e){var g=a.$a.isPublished(),k=z.Bwa(a.$a);e.HW=g&&k;if(c=z.$F(z.oC(z.nC(z.pC(z.TE(z.qC(a.Ga).jb(S6a,e),z.UE),c),{Y6:!0,Ky:!0,Ba:!0}),"popover--quoteAttributions"),d).ua())c.hm("deactivate",function(){this.Ip===b&&T7(this,null)},a),c.po().ba("quote",a.cva.bind(a,
c)).ba("quote-respond",a.dva.bind(a,c)).ba("twitter",a.eva.bind(a))}},Y6a=function(a,b){if("anon"==b.mb())return{isActive:!1,fIa:!0};var c=U7(a,b),d=b.Gd();b=b.Ce();a=H6a(a.ze,c,d,b);if(!a||!a.length)return null;a=(0,z.rb)(a,function(a){return a.user});c=(0,z.Kc)(a,function(a){return a.userId!=z.Rp().userId});return{isActive:(0,z.sc)(a,function(a){return a.userId==z.Rp().userId}),social:c,Ki:a.length}},$6a=function(a,b){a=a.we.querySelectorAll('.markup--quote[name~\x3d"'+b.ej()+'"]');return z.Va(a)},
U7=function(a,b){b=b.gc()[0].name;return(b=z.ks(a.we,b))?a.$a.cj(b):null},a7a=function(a,b){var c=z.an(b);return(c=z.BE(a.Cm,c))?G6a(a.ze,b,c):null},T7=function(a,b){a.Ip!==b&&(a.Ip&&b7a(a,a.Ip,!1),b&&b7a(a,b,!0),a.Ip=b)},b7a=function(a,b,c){$6a(a,b).map(function(a){z.Oc(a,"is-targeted",c)})},V7=function(a,b){(b=c7a(a,b))&&z.zE(a.Dk(),b)},c7a=function(a,b){var c=b.gc(),d=z.ks(a.we,c[0].getName());a=z.ks(a.we,z.Ma(c).getName());return z.QM(d,b.Gd(),a,b.Ce())},W7=function(a,b,c,d){a={postId:a.$a.Na(),
quoteId:b,source:d};z.kx(c?z.twa:z.vFa,a)},d7a=function(a){return(0,z.Kc)(z.tB(a),function(a){return 1==z.qB(a)})},e7a=function(a,b){z.sB(a,z.rB,z.Db(b,z.Cb(!0)),void 0)},f7a=function(a,b,c){z.na(a)||(a=a.toString());var d=window,e={scrollbars:!0,YKa:!0,toolbar:!1,location:!0,width:670,height:690};z.pb(e,c||{});e.left||e.top||(e.width=(0,window.parseInt)(e.width,10),e.height=(0,window.parseInt)(e.height,10),e.left=Math.max(d.screenX+Math.round(d.outerWidth/2-e.width/2),0),e.top=Math.max(d.screenY+
Math.round(d.outerHeight/2-e.height/2),0));var g={scrollbars:"scrollbars",YKa:"resizable",toolbar:"toolbar",location:"location",width:"width",height:"height",left:"left",top:"top"};c=z.qia(e,function(a,b,c){g[c]&&("boolean"==typeof b&&(b=b?"yes":"no"),a.push(g[c]+"\x3d"+b));return a},[]).join();return d.open(a,b,c)},g7a=function(a){var b=z.Nv(z.cya,{dJa:!0});b&&(b=b.split(/\s+/),b=b.filter(function(a){return!z.Aa(a)}),b.length&&z.Jc(a,b))},h7a=function(a){return(0,z.y)(z.A(z.ik(String(a.content)))+
" — "+z.A(z.Zr(a))+" "+z.A(a.url))},i7a=function(a,b,c){return(0,z.yh)("https://"+z.Fg(c.textshotHost)+"/image")},j7a=function(a,b,c){return(0,z.yh)("https://twitter.com/"+z.Fg(c.currentUser.twitterScreenName)+"/status/"+z.Fg(a.id))},k7a=function(){var a=z.y,b;b=z.n("Failed to load image");b=(0,z.y)(""+b);return a('\x3cspan class\x3d"tweetEditor-imageStatusIcon"\x3e\x26times;\x3c/span\x3e'+z.A(b))},l7a=function(a,b,c){b=z.y;a='\x3cdiv class\x3d"tweetEditor u-sizeFullWidth"\x3e\x3cdiv class\x3d"js-tweetEditor-error tweetEditor-error u-paddingBottom10 u-textAlignCenter u-textColorRed"\x3e\x3c/div\x3e\x3cdiv class\x3d"tweetEditor-avatar"\x3e'+
z.A(z.Ck({user:a.user,Cf:!0},c))+'\x3c/div\x3e\x3cdiv class\x3d"tweetEditor-tweetContainer"\x3e\x3cdiv class\x3d"tweetEditor-textContainer"\x3e\x3cdiv class\x3d"js-tweetEditor-text textInput textInput--chromeless u-textAlignLeft"\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"tweetEditor-textshot"\x3e\x3cdiv class\x3d"js-tweetEditor-imageStatus tweetEditor-imageStatus"\x3e';var d;d=z.n("Loading image attachment…");d=(0,z.y)(""+d);a=a+z.A(d)+"\x3c/div\x3e";d={};d=(0,z.y)(z.Ki(z.D({name:"addCircled",
size:"21px",content:(0,z.N)('\x3csvg class\x3d"svgIcon-use" width\x3d"21" height\x3d"21" viewBox\x3d"0 0 21 21" \x3e\x3cpath d\x3d"M2.286 12.691a8.358 8.358 0 0 0 2.192 3.831A8.298 8.298 0 0 0 8.3 18.715c.73.19 1.462.288 2.192.29a8.363 8.363 0 0 0 2.2-.29 8.286 8.286 0 0 0 3.822-2.193 8.264 8.264 0 0 0 2.201-3.82c.19-.732.285-1.462.285-2.193a8.248 8.248 0 0 0-.285-2.2 8.265 8.265 0 0 0-2.2-3.823 8.258 8.258 0 0 0-3.822-2.2A8.66 8.66 0 0 0 10.5 2a8.188 8.188 0 0 0-2.192.286 8.33 8.33 0 0 0-3.831 2.2 8.298 8.298 0 0 0-2.193 3.822A8.66 8.66 0 0 0 2 10.5c0 .731.095 1.461.286 2.191zm1.557-.413a6.74 6.74 0 0 1-.239-1.773c0-.592.08-1.184.24-1.773a6.77 6.77 0 0 1 1.786-3.09 6.73 6.73 0 0 1 3.085-1.79c.59-.16 1.181-.24 1.777-.24.596 0 1.188.08 1.777.24a6.736 6.736 0 0 1 3.094 1.786 6.801 6.801 0 0 1 1.787 3.094c.16.59.239 1.178.239 1.768 0 .59-.08 1.182-.24 1.778a6.75 6.75 0 0 1-1.786 3.093 6.801 6.801 0 0 1-3.094 1.787 6.707 6.707 0 0 1-3.545 0A6.74 6.74 0 0 1 5.63 15.37a6.746 6.746 0 0 1-1.787-3.093zm2.937-2.055c0-.134.049-.25.148-.345a.494.494 0 0 1 .359-.143H9.23a.478.478 0 0 0 .35-.148.475.475 0 0 0 .147-.35V7.303c0-.141.048-.262.144-.363a.458.458 0 0 1 .345-.152h.562c.134 0 .25.05.35.152a.502.502 0 0 1 .147.363v1.934c0 .135.048.252.143.35a.46.46 0 0 0 .345.148h1.945c.14 0 .26.048.358.143.099.096.148.21.148.345v.562a.476.476 0 0 1-.148.35.486.486 0 0 1-.358.147h-1.945a.472.472 0 0 0-.345.143.47.47 0 0 0-.143.345v1.944c0 .14-.05.262-.148.36a.478.478 0 0 1-.35.147h-.56a.498.498 0 0 1-.489-.507V11.77a.461.461 0 0 0-.148-.345.487.487 0 0 0-.35-.143H7.287a.488.488 0 0 1-.36-.147.476.476 0 0 1-.147-.35v-.562z" fill-rule\x3d"evenodd"/\x3e\x3c/svg\x3e')},
d)));d=(0,z.N)(""+z.A(d));var e;e=z.n("Include quote image");e=(0,z.y)(""+e);a=a+z.A(z.vj({icon:d,isPrimary:!0,wa:!0,l:"js-tweetEditor-addTextshot u-hide",action:"add-textshot",text:(0,z.N)(""+z.A(e))},c))+'\x3cdiv class\x3d"js-tweetEditor-imageContainer tweetEditor-imageContainer"\x3e';d=(0,z.N)("\x26times;");e=z.n("Remove quote image from tweet");e=(0,z.y)(""+e);return b(a+z.A(z.tj({s:d,Yc:!0,l:"js-tweetEditor-removeTextshot tweetEditor-removeTextshot",title:(0,z.N)(""+z.A(e)),action:"remove-textshot"},
c))+'\x3cimg class\x3d"js-tweetEditor-image tweetEditor-image" data-action\x3d"toggle-expand-image"\x3e\x3c/img\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e'+(c.variants.textshots_userid?'\x3cdiv class\x3d"u-textColorRed"\x3eTweet to test account @fuzzyoctopusfee\x3c/div\x3e':""))},m7a=function(){var a=z.n("An error occurred, and the tweet wasn’t posted to Twitter.");return(0,z.y)(""+a)},n7a=function(a,b,c){var d="";b=z.n("Tweet posted.");a=a.kMa;var e;e=z.n("View the tweet");e=(0,z.y)(""+
e);d+=b+" "+z.A(z.O({xb:!0,href:a,s:(0,z.N)(""+e)},c));return(0,z.y)(d)},o7a=function(a,b,c){a=z.n("Tweet must be {$twitterMaxTweetLength} characters or less.",{twitterMaxTweetLength:z.A(c.j.lMa)});return(0,z.y)(""+a)},p7a=function(a){if(!a)return"";var b=[],c=z.nb(["grafId","noteId","command","startIndex","endIndex"]),d;for(d in a)b[c[d]]=a[d];return b.join("-")},q7a=function(a,b){return a instanceof z.hc?z.u(a.Wc(!0),b,void 0):z.u(z.wc(a),b,void 0)},X7=function(a){z.Lw.call(this);this.Cc=a.get("dom-model-converter");
this.Cea={};this.tda={};this.Z1={};this.qa=a;this.wl=a.get("request");this.ma=a.get("route-builder");this.Aa=a.get("model-store");this.pb="";this.ffa=z.ml;this.eca=!1;this.Lh=null},Y7=function(a,b){var c=a.Cea[b];c||(c=a.Cea[b]=new z.LC,a.za("new_note_list",c,a));return c},r7a=function(a,b){if(!b)return!1;var c=b.Ia();if(a.content==c.substring(a.startIndex,a.endIndex))return!0;var d=new RegExp(z.taa(a.content),"gi"),c=(b=d.exec(c))&&d.exec(c);return b&&!c?(c=a.endIndex-a.startIndex,a.startIndex=b.index,
a.endIndex=b.index+c,a.content=b[0],!0):!1},Z7=function(a,b,c){var d=b.Na(),e=b.Eg(),g=Y7(a,b.se()),k=g?g.indexOf(b):-1,l=b.Wu();b.Aq(c);"HIDDEN"==c?a.Aa.remove(b):b=z.lC(a.Aa,b);var p=g?g.indexOf(b):-1;return{Kl:a.wl.put(a.ma.la(z.dDa,{postId:d,noteId:e}),{state:c}),JL:function(){b.Aq(l);-1==p&&(-1==k?g.add(b):z.NC(g,b,k))}}},$7=function(a,b,c,d,e,g){var k=z.J(a.Vp(c,e),"replies"),l=z.Na(k,function(a){return a.ty()==b}),p=k[l];"HIDDEN"==g&&z.Sa(k,l);c=a.ma.la(z.gDa,{postId:d,noteId:c,replyId:b});
a=a.wl.put(c,{state:g});var r=z.Na(k,function(a){return a.ty()==b});return{Kl:a,JL:function(){-1==r&&z.Ya(k,l,0,p)}}},s7a=function(a,b,c){this.range=a;this.anchor=b;this.uC=b.getAttribute("name");this.highlight=c},a8=function(a,b){z.T.call(this);this.fb=a.get("screen-request");this.xBa=b;this.iZ=[];this.nw=null;this.Mn={};this.A2=!1;this.zga=null},b8=function(a,b,c){z.T.call(this);this.Oa=a.get("screen");this.si=c;this.Va(b)},c8=function(a,b){z.T.call(this);this.Db=a.get("dom-monitor");this.Bb=a.get("element-tracker");
this.Ga=a.get("popover");this.Oa=a.get("screen");this.kw=z.QB(a.get("activity-monitor"),1E4);this.bu=a.get("placements-store");this.$a=b;this.yH=!1},t7a=function(a){var b=a.query(".js-postActionsFooter");return b?(a=z.IB(a.Bb),0>z.lw(b).top-a.height):!1},u7a=function(a){var b=a.query(".js-readNextMetabarRight");a.bu&&b&&z.u(a.bu.$r(2),function(a){a&&z.P(b,z.wP,{items:a.items,context:2})})},d8=function(a,b,c,d){z.T.call(this);this.Oa=a.get("screen");this.wp=c;this.si=d;this.eQ=!1;this.mw=this.QB=this.Yea=
null;this.Va(b)},v7a=function(a){return Math.floor((D6a(a)-a)/1E3)},e8=function(a,b,c){z.T.call(this);this.Oa=a.get("screen");this.r2=this.wp=null;this.va=b;this.$a=c;this.pa=a.get("request");this.ma=a.get("route-builder")},x7a=function(a){if(w7a(a)){var b=a.ma.la(z.$za),c=a.va.id,d=Date.now(),e=z.J(z.Gl,"meterConfig").maxUnlockCount,g=z.pD.get("mpids")?z.pD.get("mpids").split(","):[];g&&-1==g.indexOf(c)&&g.length<e&&(g.push(c),z.pD.set("mpids",g.join(","),v7a(d),"/"));return a.pa.put(b,{postIds:g})}return z.wc({})},
w7a=function(a){var b=z.Rp();return a.va&&a.va.isSubscriptionLocked&&!z.Gk(b)&&a.va.creatorId!=b.userId&&!(a.va&&3==a.va.lockedPostSource&&!z.Sp())},f8=function(a){z.T.call(this);this.bu=a.get("placements-store")},y7a=function(a){a.bu&&z.u(a.bu.$r(1),function(b){b&&z.P(a.oa(),z.wP,{items:b.items,context:9})})},g8=function(a){z.T.call(this);this.Bb=a.get("element-tracker");this.QR=this.cu=null;this.cI=[];this.Fr=0;this.b4=z7a;this.k_=this.l_=null},h8=function(a){z.T.call(this);this.bu=a.get("placements-store");
this.Bb=a.get("element-tracker");this.cu=null;this.cI=[];this.Fr=this.rR=null},A7a=function(a){a.bu&&z.u(z.u(a.bu.$r(3),function(b){if(b)return z.P(a.oa(),z.wP,{items:b.items,context:44}),z.Nw(a,a.Bb,"refresh",a.Zga.bind(a)),a.Bb.Mk()}),a.Zga,a)},B7a=function(a){var b=z.DB(a.Bb,a.cu),c=z.ZA(b)+b.We()/3,b=d7a(a.cu).map(function(b){return[b,z.DB(a.Bb,b)]}).filter(function(a){a=z.ha(a);var b=a.next().value;return z.ZA(a.next().value)<c&&!z.Ds(z.zB(b))}),d=a.rR.fd();return(b=b.map(function(a){var b=z.ha(a);
a=b.next().value;var c=b.next().value,b=d.clone(),c=z.ZA(c);a=z.xn(a).top||0;b.top=c+a;return b}).find(function(b){return!a.R0(b)}))?b.top:null},i8=function(a,b){z.T.call(this);this.qa=a;this.Bb=a.get("element-tracker");this.$a=b;this.l2=this.$a.sm;this.t2=this.gR=this.eR=null},j8=function(){},C7a=function(a){this.OQ=a},k8=function(a,b){return b?z.ks(a.OQ,b):null},D7a=function(a,b,c){e7a(a.OQ,function(a){var e=a.getAttribute("name");e&&b.call(c,a,e)})},E7a=function(a,b){return z.Tf(a.OQ,b)?a.OQ:null},
l8=function(a,b,c,d,e){z.WW.call(this,a,b);this.cb(new z.oW(c));this.cb(new z.jX(!1));this.cb(new z.mX(a));this.cb(new z.XW);this.cb(new z.pX(a,!1,!1));this.cb(new z.pU(d,!0));this.sl=!0;this.Bm=d;this.wl=a.get("request");this.Ea=a.get("dialog");this.D1=e;this.ua()},F7a=function(){var a=z.n("Saving failed. You may be having connectivity issues or notes might be disabled on this post. Please try again.");return(0,z.y)(""+a)},G7a=function(){var a=z.n("Yikes! Something happened and we couldn’t dismiss this note.");
return(0,z.y)(""+a)},H7a=function(){var a=z.n("Yikes! Something happened and we couldn’t delete this note.");return(0,z.y)(""+a)},I7a=function(){var a=z.n("Yikes! Something happened and we couldn’t delete this reply.");return(0,z.y)(""+a)},J7a=function(){var a=z.n("The note has been dismissed.");return(0,z.y)(""+a)},K7a=function(){var a=z.n("The note has been deleted.");return(0,z.y)(""+a)},L7a=function(){var a=z.n("The reply has been deleted.");return(0,z.y)(""+a)},M7a=function(){var a=z.n("Write a note…");
return(0,z.y)(""+a)},N7a=function(){var a=z.n("Cancel");return(0,z.y)(""+a)},m8=function(a,b,c,d,e){l8.call(this,a,b,e||"Leave a note",400,d||null);this.pb=c;this.ma=a.get("route-builder");this.Af=a.get("notes-data")},n8=function(a,b,c,d,e,g){l8.call(this,a,b,"Leave a reply…",200,d);this.ma=a.get("route-builder");this.Af=a.get("notes-data");this.pb=c;this.Ffa=g||null;this.Re=e},P7a=function(a,b,c){var d='\x3cdiv class\x3d"quoteResponses js-quoteResponses"\x3e',e=a.quotes.length,g=a.responses.length||
a.i$;b=a.notes.length||a.EW;if(e||g||b){if(e){var e='\x3cdiv class\x3d"quoteResponses-section"\x3e'+z.A(z.Qy({title:(0,z.N)(z.A(V6a())+" ("+z.A(a.quotes.length)+")"),Xf:!0},c)),k;k={Qla:a.quotes,IMa:!0};var l='\x3cdiv class\x3d"js-quotesList"\x3e';if(!k.IMa)var p=z.n("Learn more"),l=l+z.A(z.Qy({title:(0,z.N)(""+z.A(V6a())),Xf:!0,Wg:(0,z.N)(""+z.A(z.Py({href:(0,z.M)(""+z.G((0,z.yh)("https://medium.com/the-story/introducing-highlights-a4df69e8ed43"))),moreText:(0,z.N)(""+p),wb:!0},c)))},c));for(var p=
"list u-marginTop5 u-marginBottom15"+(k.Qla.length?"":" u-hide"),p=(0,z.N)(p),l=l+('\x3cul class\x3d"'+z.F(p)+'"\x3e'),p=k.Qla,r=p.length,t=0;t<r;t++){for(var w=p[t],B="",H=w.quotes,Q=H.length,R=0;R<Q;R++)B+=""+H[R].quoteId+(R!=Q-1?",":"");B=z.E(B);l+='\x3cli class\x3d"list-item list-item--inline u-border0" data-quote-ids\x3d"'+z.F(B)+'" data-quote-creator-id\x3d"'+z.F(w.user.userId)+'" data-action\x3d"highlight-quote" data-action-type\x3d"hover"\x3e'+z.A(z.xk(z.D({user:w.user,He:!0},k),c))+"\x3c/li\x3e"}k=
(0,z.y)(l+"\x3c/ul\x3e\x3c/div\x3e");e=e+z.A(k)+"\x3c/div\x3e"}else e="";g?(g='\x3cdiv class\x3d"quoteResponses-section'+(a.i$?" is-withEditor":"")+'"\x3e'+z.A(z.Qy({title:(0,z.N)(""+z.A(z.jk())),Xf:!0},c)),a.i$&&c.supportsEdit&&c.isAuthenticated?(k={},k=(0,z.y)('\x3cdiv class\x3d"js-inlineNewPostControl inlineNewPostControl inlineNewPostControl--quoteResponses"\x3e'+z.TO(z.D({user:c.currentUser,isCollapsed:!0,FD:!0,type:"quoteResponses",uv:(0,z.N)(""+z.A(z.Zfa()))},k),c)+"\x3c/div\x3e"),k=z.A(k)):
k="",g=g+k+O7a(a,0,c)+"\x3c/div\x3e"):g="";d+=e+g;if(a.jKa&&b){g=z.n("Who can see this?");d+='\x3cdiv class\x3d"quoteResponses-section quoteResponses-section--fullBleed u-paddingLeft0 u-paddingRight0"\x3e';e=b="";k=a.post.homeCollection;k=a.post.creator.userId!=c.currentUser.userId?k?z.n("Private notes are visible to you, the author, and the editors of {$name}.",{name:z.A(k.name)}):z.n("Private notes are visible to you, the author, and the editors of any publication this story is added to."):k?z.n("Private notes are visible to you and the editors of {$name}.",
{name:z.A(k.name)}):z.n("Private notes are visible to you and the editors of any publication this story is added to.");e+=k;e=(0,z.y)(e);e=""+z.A(e);e=(0,z.N)(e);b+='\x3cspan data-tooltip\x3d"'+z.F(e)+'"\x3e'+g+"\x3c/span\x3e";g={};g=(0,z.y)(z.Ki(z.D({name:"lock",size:"19px",content:(0,z.N)('\x3csvg class\x3d"svgIcon-use" width\x3d"19" height\x3d"19" viewBox\x3d"0 0 19 19" \x3e\x3cpath d\x3d"M14 14.052a1 1 0 0 1-.992.998H5.992A.99.99 0 0 1 5 14.052v-4.004a1 1 0 0 1 .992-.998h7.016a.99.99 0 0 1 .992.998v4.004zM7 5.445C7 4.187 8.114 3.15 9.5 3.15c1.385 0 2.5 1.04 2.5 2.295V8.05H7V5.445zm6.008 2.605H13V5.445c0-1.822-1.578-3.295-3.5-3.295C7.577 2.15 6 3.618 6 5.445V8.05h-.008A2 2 0 0 0 4 10.048v4.004a1.99 1.99 0 0 0 1.992 1.998h7.016A2 2 0 0 0 15 14.052v-4.004a1.99 1.99 0 0 0-1.992-1.998z" fill-rule\x3d"evenodd"/\x3e\x3c/svg\x3e')},
g)));g=(0,z.N)(""+z.A(g));e=z.n("Private notes");e=(0,z.y)(""+e);b={eMa:g,title:(0,z.N)(""+z.A(e)),Xf:!0,Wg:(0,z.N)(b),l:"heading--privateNotes"};b=(0,z.y)(z.Ny(z.D({Xi:(0,z.N)(""+z.Oy(b,c)),XIa:!0},b)));b=d+=z.A(b);d=""+('\x3cdiv class\x3d"privateNotes-list js-notesList'+(a.EW?" is-showingNoteEditor":"")+(0==a.notes.length?" is-empty":"")+'"\x3e');g=a.notes;e=g.length;for(k=0;k<e;k++)d+=o8({note:g[k],post:a.post,oM:a.oM},0,c);a.EW?(g=a.post.creator,a="",g=c.currentUser.userId==g.userId?z.n("Leave yourself a note"):
z.n("Send {$name} a private note…",{name:z.A(g.name)}),a+=g,a=(0,z.y)(a),a='\x3cdiv class\x3d"privateNotes-actions js-noteActions"\x3e'+z.A(z.uj({action:"show-note-editor",text:(0,z.N)(""+z.A(a)),l:"privateNotes-prompt"},0,c)),g=z.y,e='\x3cdiv class\x3d"privateNotes-editor"\x3e'+z.A(z.Bk({user:c.currentUser,Cf:!0},c))+'\x3cdiv class\x3d"js-noteEditor"\x3e\x3c/div\x3e\x3cdiv class\x3d"buttonSet"\x3e',k=z.n("Send"),k=(0,z.y)(""+k),c=g(e+z.A(z.uj({action:"save-note",isPrimary:!0,l:"js-saveNoteButton",
text:(0,z.N)(""+z.A(k))},0,c))+z.A(z.uj({action:"hide-note-editor",text:(0,z.N)(""+z.A(N7a()))},0,c))+"\x3c/div\x3e\x3c/div\x3e"),c=a+c+"\x3c/div\x3e"):c="";c=(0,z.y)(d+("\x3c/div\x3e"+c));d=b+('\x3cdiv class\x3d"quoteResponses-inner privateNotes"\x3e'+c+"\x3c/div\x3e\x3c/div\x3e")}}else 0<a.FE&&(a=z.n("Show next tip"),b=z.n("Show previous tip"),d+='\x3cdiv class\x3d"quoteResponses-section quoteResponses-section--fullBleed quoteResponses-section--tips u-textAlignCenter u-paddingLeft0 u-paddingRight0"\x3e\x3cdiv class\x3d"quoteResponses-section--tipsInner u-alignMiddle"\x3e'+
z.A(z.vj({Hb:!0,Yc:!0,wa:!0,action:"previous-highlight-tip",icon:(0,z.N)(""+z.A(z.Wda())),title:(0,z.N)(""+b)},c))+"\x3cdiv class\x3d'u-alignBlock quoteResponses-section--tipsContent u-paddingLeft20 u-paddingRight20 js-highlightTip'\x3e\x3c/div\x3e"+z.A(z.vj({Hb:!0,Yc:!0,wa:!0,action:"next-highlight-tip",icon:(0,z.N)(""+z.A(z.Xda())),title:(0,z.N)(""+a)},c))+"\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e");return(0,z.y)(d+"\x3c/div\x3e")},O7a=function(a,b,c){return(0,z.y)(z.A(z.AP({posts:a.responses,source:"quoteResponses",
JU:!0},0,c)))},o8=function(a,b,c){var d,e=null==a.note.replies?null:a.note.replies.length,g=null==a.note.replyId,k=a.post.creator.userId==c.currentUser.userId,l=a.post.creator.userId==a.note.author.userId;d=a.note.author.userId==c.currentUser.userId;b=k||(null==a.post.homeCollection?null:a.post.homeCollection.virtuals.permissions.canEditPosts);var p=""+(g?"js-note-item"+(a.note.noteId?" js-note-"+a.note.noteId:""):"js-reply-item"+(a.note.replyId?" js-reply-"+a.note.replyId:"")),p=z.E(p),p='\x3cdiv class\x3d"privateNotes-item '+
z.F(p)+' js-note" data-note-id\x3d"'+z.F(a.note.noteId)+'"\x3e'+(g?z.A(z.xk({user:a.note.author},c)):z.A(z.RN({user:a.note.author},c)))+'\x3cdiv class\x3d"privateNotes-authorLockup"\x3e\x3cdiv class\x3d"privateNotes-author"\x3e'+z.A(z.Vj({user:a.note.author},c));g||!(k||d||(null==a.post.homeCollection?0:a.post.homeCollection.virtuals.permissions.canEditPosts))||l||a.tka?k="":(k=z.n("(Editor)"),k=(0,z.y)(""+k),k='\x3cspan class\x3d"privateNotes-author--supplemental"\x3e '+z.A(k)+"\x3c/span\x3e");p=
p+k+'\x3c/div\x3e\x3cdiv class\x3d"privateNotes-supplemental"\x3e'+z.A(z.Zg(Number(a.note.createdAt),c))+'\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"privateNotes-content js-privateNotesContent"\x3e';k=z.A(z.Kt(String(a.note.content),c));l=String(k).replace(/(\r\n|\r|\n)/g,"\x3cbr\x3e");k=z.dg(k,z.fg)?(0,z.y)(l,z.Eca(k)):l;d=""+(p+k+"\x3c/div\x3e"+(d?Q7a({note:a.note,isPrimary:g},c):""));if(g){d+='\x3cdiv class\x3d"privateNotes-replies'+(e?"":" is-empty")+' js-repliesList"\x3e';if(e)for(e=a.note.replies,
g=e.length,p=0;p<g;p++)k=e[p],d+=o8({note:k,post:a.post,tka:a.note.author.userId==k.author.userId},0,c);e=d;a.oM?(g=z.y,d='\x3cdiv class\x3d"privateNotes-editor privateNotes-editor--reply"\x3e'+z.A(z.GP({user:c.currentUser,Cf:!0},c))+'\x3cdiv class\x3d"js-replyEditor"\x3e\x3c/div\x3e\x3cdiv class\x3d"buttonSet"\x3e',p=z.n("Send"),p=(0,z.y)(""+p),g=g(d+z.A(z.uj({action:"save-reply",isPrimary:!0,text:(0,z.N)(""+z.A(p))},0,c))+z.A(z.uj({action:"hide-reply-editor",text:(0,z.N)(""+z.A(N7a()))},0,c))+"\x3c/div\x3e\x3c/div\x3e")):
g="";g="\x3c/div\x3e"+g+'\x3cdiv class\x3d"privateNotes-actions'+(b?" privateNotes-actions--withDismiss":"")+' u-clearfix"\x3e';a.oM?(d=z.y,p=z.n("Reply"),p=(0,z.y)(""+p),d='\x3cdiv class\x3d"u-floatLeft"\x3e'+d(z.A(z.uj({isPrimary:!0,action:"show-reply-editor",l:"privateNotes-prompt",text:(0,z.N)(""+z.A(p))},0,c)))+"\x3c/div\x3e"):d="";d=e+(g+d+(b?'\x3cdiv class\x3d"u-floatRight"\x3e'+Q7a({note:a.note,isPrimary:!0,aka:!0},c)+"\x3c/div\x3e":"")+"\x3c/div\x3e")}return(0,z.y)(d+"\x3c/div\x3e")},Q7a=
function(a,b){var c=z.y,d=a.isPrimary?a.note.noteId:a.note.replyId,e=a.aka?"dismiss-note":a.isPrimary?"delete-note":"delete-reply";a=a.aka?z.n("Dismiss note"):z.n("Delete");a=(0,z.y)(""+a);a=z.A(a);return c(z.A(z.uj({actionValue:d,action:e,l:"privateNotes-delete js-deleteNote",text:(0,z.N)(""+a)},0,b)))},R7a=function(a,b,c){b="";if(0==a.U9)a=1==a.FE?z.n("People highlighted this passage. You can click on an existing highlight to add to it, like below:"):z.n("{$topQuoteCount} people highlighted this passage. You can click on an existing highlight to add to it, like below:",
{topQuoteCount:z.A(a.FE)}),b+=a,b+='\x3cimg class\x3d"quoteResponses-tipAnimation" src\x3d"'+z.F(z.Ig(z.vi({imageId:"1*SyXCciYXeNpx4-GUAuh0XQ.gif"},0,c)))+'"\x3e';else if(1==a.U9)a=z.n("Or, select any passage to create your own highlight and tell the author and others what resonated with you:"),b+=a+'\x3cimg class\x3d"quoteResponses-tipAnimation" src\x3d"'+z.F(z.Ig(z.vi({imageId:"1*dEp02HXMKtAeKxsV5MWqGg.gif"},0,c)))+'"\x3e';else if(2==a.U9){a=z.n("so that you can save your highlights and share them with others.");
var d=z.n("Sign up and create a profile");b+=z.A(z.uj({text:(0,z.N)(""+d),ac:!0,source:(0,z.N)(""+z.A(z.Ch({name:c.j.oc.Noa,susiEntry:c.j.Ha.lF}))),l:"u-textUnderline"},0,c))+" "+a}return(0,z.y)(b)},p8=function(a,b,c,d,e,g,k,l){z.T.call(this);this.qa=a;this.xa=a.get("butter-bar");this.$a=b;this.Re=c;this.hk=e;this.ze=a.get("quotes-data");this.Af=a.get("notes-data");this.Dj=a.get("responses-data");this.pf=g;this.D1=d;this.J2=(this.DI=k)?k.ej():null;this.Of=this.Lc=null;this.lk={};this.Fda=!!z.Sp();
this.Gda=!!z.Up();this.rB=this.Fda&&this.Gda&&z.LE(b);this.gr=null;this.RP=0;this.Oga=I6a(this.ze,this.Re);this.Rw=l;this.Va(this.Wq());this.Gea=z.Sp()?2:3},S7a=function(a){a.ob(".js-block").forEach(function(a){this.Ta(a,"mouseenter",this.Eva,this);this.Ta(a,"mouseleave",this.c4,this)},a)},T7a=function(a){a.ob(".js-note").forEach(function(a){this.Ta(a,"mouseenter",this.Cva,this);this.Ta(a,"mouseleave",this.c4,this)},a)},U7a=function(a,b){var c=a.query(".js-note-"+b);a.lk[b]||(a.lk[b]=new n8(a.qa,
c.querySelector(".js-replyEditor"),a.$a.Na(),b,a.Re),z.Nw(a,a.lk[b],"saving",a.Yya,a),z.Nw(a,a.lk[b],"save",a.Tya,a),z.Nw(a,a.lk[b],"fail",a.Rxa,a));z.Ic(c,"is-noteEditorVisible");a.lk[b].focus()},V7a=function(a,b){var c=a.lk[b];c&&(c.ib()&&c.jd(""),a=a.query(".js-note-"+b),z.Mc(a,"is-noteEditorVisible"))},W7a=function(a,b,c){var d=k8(a.pf,a.Re);if(d){var e=[];a.Rw&&(e=a.Rw.quotes.map(function(a){return a.ej()}));(0,z.rb)(d.querySelectorAll(".markup--quote"),function(a){var d=a.getAttribute("data-creator-ids").split(" "),
d=z.Ra(d,b);if(this.Rw)var l=a.getAttribute("name").split(" "),d=d&&(0,z.sc)(l,z.Ra.bind(null,e));z.Oc(a,"is-selected",c&&d)},a)}},q8=function(a){return(a=z.hs(a,function(a){return z.Hc(a,"js-note-item")}))&&a.getAttribute("data-note-id")},X7a=function(a,b,c,d){b=new z.rE(b,300);b.Va(c);b.subscribe("dismiss",d,a);b.ua();return b},r8=function(a){var b=a.gc(),c=a.Gd();a=a.Ce();1<b.length&&(a=b[0].Ia().length);var d=new z.Tr;d.wq(b[0].getName());d.Kg(c);z.K(d,"endIndex",a);d.jd(b[0].Ia().substring(c,
a));return d},s8=function(a,b){b%=a.Gea;0>b&&(b=a.Gea-1);a.RP=b;(b=a.query(".js-highlightTip"))&&z.P(b,R7a,{U9:a.RP,FE:a.Oga})},t8=function(a,b,c,d){z.T.call(this);this.Va(this.Wq(d));this.Db=a.get("dom-monitor");this.$a=b;this.Lda=!b.Za().Yr()||b.Pb();this.pb=b.Na();this.pf=c;this.ze=a.get("quotes-data");this.Dj=a.get("responses-data");this.Af=a.get("notes-data");this.ww=null;this.Oh={}},Y7a=function(a,b){b.forEach(function(a){a&&u8(this,a)},a)},u8=function(a,b){if(!a.ww)if(k8(a.pf,b)){var c=Z7a(a,
b),c=$7a(a,c),c=a8a(a,c),c=b8a(a,c);a.Oh[b]=c;c8a(a,b)}else delete a.Oh[b]},d8a=function(a,b){if(!a.ww){var c=a.Oh[b];if(c){var d=c.length,c=a8a(a,c),c=b8a(a,c);a.Oh[b]=c;d!=c.length?c8a(a,b):c.forEach(function(a){a.Xa&&a.offsetTop&&(a.Xa.style.top=a.offsetTop+"px")})}}},e8a=function(a,b,c){return z.Oa(a.Oh[b]||[],function(a){return a.Xa==c})},Z7a=function(a,b){var c=[];Y7(a.Af,b).Zg(function(a){var e=a.bD(),g;e?(g=this.Af.dU(e),e=g.kb(),g=z.J(g,"endIndex")):(e=0,g=a.ib().length);c.push({anchor:b,
startIndex:e,endIndex:g,notes:[a],quotes:[],responses:[]})},a);if(a.Lda)return c;(a.ze.gu[b]||[]).forEach(function(a){var e=f8a(a);c.push({anchor:b,startIndex:e.startIndex,endIndex:e.endIndex,notes:[],quotes:[a],responses:[]})},a);M7(a.Dj,b).forEach(function(a){var e=K7(a);e&&(e=L7(e)&&L7(e).oo())&&(e=f8a(e),c.push({anchor:b,startIndex:e.startIndex,endIndex:e.endIndex,notes:[],quotes:[],responses:[a]}))},a);return c},$7a=function(a,b){var c=[];b.sort(function(a,b){return a.startIndex-b.startIndex});
b.forEach(function(a){var b=z.Na(c,function(b){return b.endIndex>=a.startIndex-1&&b.startIndex<=a.endIndex+1});0<=b?this.YH(c[b],a):c.push(a)},a);return c},b8a=function(a,b){var c=[];b.forEach(function(a){if(a.offsetTop){var b=z.Na(c,function(b){return 30>=Math.abs(b.offsetTop-a.offsetTop)});0<=b?this.YH(c[b],a):c.push(a)}},a);return c},c8a=function(a,b){a.ob(".js-paragraphControl-"+b).forEach(z.Ef);a.Oh[b]=a.Oh[b].map(function(a){var b=g8a(this,a),b=z.Ov(h8a,b);b.style.top=a.offsetTop+"px";a.Xa=
b;this.oa().appendChild(a.Xa);z.Ic(b,"is-visible");return a},a)},g8a=function(a,b){var c=b.notes,d=b.responses,e=G7(a.ze,b.quotes),g=d?d.length:0,k=c?c.length:0,l=0,p=0,r=0,t=!1,w=!1,B={},H={},Q=z.Rp().userId,R=a.$a.Za().Ef().mb();c.forEach(function(a){var b=a.eK();b&&((a=z.J(a,"replies"))&&a.forEach(function(a){k++;a.author&&(a.author.userId==Q&&l++,a.author.social&&a.author.social.isFollowing&&(B[a.author.userId]=a.author),H[a.author.userId]=!0)}),H[b.userId]=!0,b.userId==Q&&l++,b.userId==R?p++:
r++,b.social&&b.social.isFollowing&&(B[b.userId]=b))});e.forEach(function(a){a=a.user;H[a.userId]=!0;a.userId==Q&&(t=!0);a.social&&a.social.isFollowing&&(B[a.userId]=a)});d.forEach(function(a){a=a.Ef();H[a.userId]=!0;a.userId==Q&&(w=!0);a.social&&a.social.isFollowing&&(B[a.userId]=a)});c=b.quotes.filter(function(a){return"anon"==a.mb()});return{postId:a.pb,uC:b.anchor,hKa:k,ZKa:g,ez:w,Wy:l,lla:p,iKa:r,i3a:e.length,dz:t,Pja:Object.keys(H).length,XHa:z.gb(B),FE:c.length}},f8a=function(a){var b=a.Gd(),
c=a.Ce();1<a.paragraphs.length&&(c=a.paragraphs[0].text.length);return{startIndex:b,endIndex:c}},a8a=function(a,b){var c=z.iw();return b.map(function(a){var b=this.pf.get(a.anchor),g=this.$a.cj(b);if(!g)return a;var k;4==g.type&&(g.Ia()&&(k=b.querySelector("figcaption")),k||(k=b));if(!k){g=a.startIndex+1;b=[b];k=0;for(var l=null;0<b.length&&k<g;)if(l=b.pop(),!(l.nodeName in z.FKa))if(3==l.nodeType){var p=l.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," ");k+=p.length}else if(l.nodeName in z.YQ)k+=
z.YQ[l.nodeName].length;else for(p=l.childNodes.length-1;0<=p;p--)b.push(l.childNodes[p]);k=l}g=z.lw(k,!0);a.offsetTop=Math.round(g.top+c.top);return a},a)},h8a=function(a,b,c){b=z.y;var d='\x3cdiv class\x3d"paragraphControls js-paragraphControl js-paragraphControl-'+z.F(a.uC)+' u-noUserSelect"\x3e',e=z.y,g;if(a.hKa||a.ZKa){g='\x3cdiv class\x3d"notesMarker u-noUserSelect" data-action\x3d"select-anchor" data-action-value\x3d"'+z.F(a.uC)+'"\x3e';var k;k={};k=(0,z.y)(z.Ki(z.D({name:"asteriskFilled",
size:"19px",content:(0,z.N)('\x3csvg class\x3d"svgIcon-use" width\x3d"19" height\x3d"19" viewBox\x3d"0 0 19 19" \x3e\x3cpath d\x3d"M14.78 8.07a8.681 8.681 0 0 0-.427-1.383.478.478 0 0 0-.584-.27l-3.12.77V4.034c0-.247-.19-.48-.43-.5a7.23 7.23 0 0 0-1.38 0c-.24.02-.43.253-.43.5V7.19L5.3 6.415a.48.48 0 0 0-.583.27c-.18.448-.324.91-.426 1.383-.05.24.1.5.32.58l3.06.754-1.98 2.956c-.14.196-.13.502.04.67.34.332.7.632 1.09.896.2.136.49.077.63-.117l2.09-3.114 2.09 3.112c.15.193.43.252.63.116.39-.26.75-.56 1.09-.89.17-.17.19-.47.04-.67L11.4 9.41l3.06-.76a.517.517 0 0 0 .32-.58" fill-rule\x3d"evenodd"/\x3e\x3c/svg\x3e')},
k)));g=g+z.A(k)+"\x3c/div\x3e"}else g="";var l=k="",p="",r=1==a.Wy?z.n("a note"):z.n("notes"),p=p+(""+r),p=z.E(p);1==a.Pja&&(0<a.Wy||a.dz||a.ez)&&(0<a.Wy&&a.dz&&a.ez?(p=z.n("highlighted, responded, and left {$noteCountText}",{noteCountText:""+p}),l+=" "+p):0<a.Wy&&a.ez?(p=z.n("responded and left {$noteCountText}",{noteCountText:""+p}),l+=" "+p):0<a.Wy&&a.dz?(p=z.n("highlighted and left {$noteCountText}",{noteCountText:""+p}),l+=" "+p):a.dz&&a.ez?(p=z.n("highlighted and responded"),l+=" "+p):a.dz?
(p=z.n("highlighted"),l+=" "+p):0<a.Wy?(p=z.n("left {$noteCountText}",{noteCountText:""+p}),l+=" "+p):a.ez&&(p=z.n("responded"),l+=" "+p));l=z.E(l);k+='\x3cspan class\x3d"paragraphControls-itemText"\x3e';p="";if(0<a.lla&&0==a.iKa&&!a.dz&&!a.ez)c=1==a.lla?z.n("Note to self"):z.n("Notes to self"),p+=c;else{r="";if(0<a.FE)var t=z.n("Top highlight"),r=r+t;p+=z.A(z.jP(z.D({social:a.XHa,isActive:0<a.Wy||a.dz||a.ez,Ki:a.Pja,o7:!0,uKa:!0,nia:(0,z.N)(r)},a),c));p+=z.A(l)}p=(0,z.N)(p);k+=z.A(z.YIa(z.D({text:p},
a)))+"\x3c/span\x3e";a=(0,z.y)(k);a=e(g+a);return b(d+a+"\x3c/div\x3e")},v8=function(a,b,c){z.T.call(this);this.qa=a;this.Ja=a.get("app");this.kua=a.get("floating-components");this.Oa=a.get("screen");this.ub=a.get("screen-service");this.Db=a.get("dom-monitor");this.$a=b;this.we=b.we;this.sm=this.we.querySelector(".js-postField");this.Zea=this.Oa.oa().querySelector(".js-notesPositionContainer");this.ze=a.get("quotes-data");this.Af=a.get("notes-data");this.Af.subscribe("new_note_list",this.oya,this);
this.Dj=a.get("responses-data");this.qm=null;this.pf=new C7a(this.we.querySelector(".js-notesSource"));this.WH=this.Oh=this.RR=null;this.Oh=new t8(a,b,this.pf,this.Zea);this.track(this.Oh);this.WH=this.Oh.oa();this.rm=this.d1=null;this.Ue=c},x8=function(a,b){if(a.isActive()){var c=(b=b||a.d1)&&b.xU,d=b&&b.noteId;c&&(a.sx(c),d&&a.Af.Vp(d,c)&&a.rm&&z.u(a.rm,function(){return w8(a,c,null,d)}));z.zoa(a.Ja,"")}else a.d1=b||null},w8=function(a,b,c,d,e,g){var k={Zl:!0,f7:z.Sv()};a.R2();c=new p8(a.qa,a.$a,
b,d||"",c||null,a.pf,e||null,g||null);c.subscribe("set-active-highlight",a.Vfa,a);c.subscribe("reset-highlight",a.FBa,a);c.subscribe("close",a.R2,a);b=g&&g.Xa?g.Xa:a.pf.get(b);g=z.Fya(a.kua);g.Un=b;b=g.QE(c);b.pJ=k;k=b.kX(a.Pn.bind(a));k.xR=!0;a.qm=k.ua()},i8a=function(a,b,c){var d=a.$a.cj(k8(a.pf,b));if(d&&4!=d.type){z.Rs(d,4);if(c){if(!r7a(c,d))return;z.Ps(d,z.ys(c.startIndex,c.endIndex,c.id))}c=a.$a.Pb();var e=a.$a.Za();c={mode:c?"edit":"view",Sj:z.dt(e),media:null,dm:null,sections:!0,Nk:!1,Kk:!1,
Hl:!1,Sf:!1,postId:e.id};a.pf.get(b).innerHTML=z.At(d,z.Gl,c)}},j8a=function(a,b){var c=z.$m();if(!c||c.isCollapsed())if(b&&(c=b),!c||c.isCollapsed())return null;b=c.Vf();var d=E7a(a.pf,b);if(!d)return null;a=(b=z.hs(b,z.rB,d))&&a.$a.cj(b);if(!b)return null;var d=z.nw(c,b,!0),e=z.nw(c,b,!1);return-1==d||-1==e?null:new s7a(c,b,new z.Tr({anchor:b.getAttribute("name"),startIndex:d,endIndex:e,content:a.Ia().substring(d,e)}))},k8a=function(){},y8=function(a,b){z.T.call(this);this.Sh=b||W6a;this.fb=a.get("screen-request");
this.va=null;this.m4=a.get("screen-view-state");this.qa=a;this.iga=this.r3=!1;this.X1=this.Lc=null},z8=function(a){z.Lw.call(this);this.Cz=a},l8a=function(a,b,c){a=z.na(a)?new z.td(a):a;(a=f7a(a,b,c||{}))&&(new z8(a)).focus()},m8a=function(a){this.pa=a.get("request");this.ma=a.get("route-builder")},A8=function(a){z.Il.call(this);this.qa=a;this.zG=a.get("dialog");this.pa=a.get("request");this.ma=a.get("route-builder");this.xa=a.get("butter-bar");this.wJ=this.Ea=this.Jx=this.va=null;this.WP=!1},o8a=
function(a){var b=a.Ea.query(".js-tweetEditor-image"),c=a.Ea.query(".js-tweetEditor-imageContainer"),d=a.Ea.query(".js-tweetEditor-imageStatus");z.Ic(c,"u-hide");var e=n8a(a);e.base64=!0;z.v(z.u(a.pa.post(z.Nv(i7a),e,{vC:!1,withCredentials:!1}),function(a){b.src="data:image/png;base64,"+a;z.Mc(c,"u-hide");z.Ic(d,"u-hide");this.WP=!0},a),function(a){z.Hw(a);z.P(d,k7a)},a)},p8a=function(a,b){return 280>=O7(b)?!0:(b=a.Ea.query(".js-tweetEditor-text"),(new z.rz(b,{name:"shimmy-shake",duration:400})).start(),
a=a.Ea.query(".js-tweetEditor-error"),z.P(a,o7a),!1)},n8a=function(a){var b=a.va,c=a.Jx.bMa;a=a.Jx.aMa;var d=b.creator,e=b.approvedHomeCollection,g=z.Gl,k=null;e&&(k=e.image);var l=null;e&&e.logo&&e.logo.imageId&&(l=e.logo.imageId);var p=null;e&&e.tintColor&&2==e.colorBehavior&&e.logo&&e.logo.imageId&&(p=e.tintColor);var r=null;e&&e.tintColor&&(r=z.wKa(e.tintColor),r=z.Fr(r,.6).color);return new P7({content:c,altText:a,title:b.title,author:d&&d.name,date:z.Yg(b.createdAt,g),authorAvatarId:d&&d.imageId,
collection:e&&e.name,collectionAvatarId:k?k.imageId:null,collectionLogoId:l,collectionBackgroundColor:p,collectionHighlightColor:r,version:2})},q8a=function(a){this.pa=a.get("request");this.ma=a.get("route-builder");this.qa=a},r8a={mTa:1,oTa:2,nTa:3,pTa:4,qTa:5,lTa:6,$isProtoEnum:!0};z.q(D7,z.L);z.f=D7.prototype;z.f.ca=function(){return""};z.f.ea=function(){return""};z.f.Dv=z.h(314);z.f.Fd=z.h(440);z.f.Rb=z.h(444);z.f.ha=function(){return D7.prototype};
z.f.fa={name:"PlacementSlot",ia:!1,fields:{location:{name:"location",g:function(){return r8a},h:1},index:{name:"index",g:z.X,h:2}},ka:{}};z.f.Rb=z.Y(444,function(a){return z.K(this,"index",a)});z.f.Fd=z.Y(440,function(){return z.J(this,"index")});z.q(E7,z.L);z.f=E7.prototype;z.f.ca=function(){return""};z.f.ea=function(){return"Placement"};z.f.uf=function(){return z.J(this,"items")};z.f.Nc=z.h(394);z.f.Dv=z.h(313);z.f.Fd=z.h(439);z.f.Rb=z.h(443);z.f.ha=function(){return E7.prototype};
z.f.fa={name:"Placement",ia:!1,fields:{items:{name:"items",g:function(){return z.UL},ra:z.V,h:1},location:{name:"location",g:function(){return r8a},h:2},index:{name:"index",g:z.X,h:3}},ka:{}};z.f.Rb=z.Y(443,function(a){return z.K(this,"index",a)});z.f.Fd=z.Y(439,function(){return z.J(this,"index")});z.f.Nc=z.Y(394,function(a){return z.K(this,"items",a)});z.m(H7,z.Zd);H7.prototype.Ck=function(a){var b={};z.lD(this,b,a.Vb(),"");return b};
H7.prototype.Kb=function(a,b){if(!a||!b)return null;var c=new a;Object.keys(b).forEach(function(a){for(var e=a.split(/[[\]]+/).filter(function(a){return!!a}),g=c,k=e.shift();k;){var l=z.sh(g,k);if(!l)break;var p=l.g();if(l.ra()){var r=z.oh(g,k)||[],t=e.shift(),w=Number(t);if(void 0===t||!Number.isInteger(w)||0>w)break;if(p.prototype instanceof z.eh)l=r[w],l||(l=new p,r[w]=l),z.K(g,k,r),g=l;else{if(void 0!==e.shift())break;p=y6a(b[a],l);r[w]=p;z.K(g,k,r)}}else if(p.prototype instanceof z.eh)r=z.oh(g,
k),r||(r=new p,z.K(g,k,r)),g=r;else{if(void 0!==e.shift())break;p=y6a(b[a],l);z.K(g,k,p)}k=e.shift()}});return c};z.q(I7,z.uh);z.f=I7.prototype;z.f.ca=function(){return""};z.f.ea=function(){return""};z.f.$r=z.h(583);z.f.yW=z.h(435);z.f.ha=function(){return I7.prototype};z.f.fa={name:"PlacementsResponse",ia:!1,fields:{placements:{name:"placements",g:function(){return E7},ra:z.V,h:1},stateParams:{name:"stateParams",g:function(){return z.LM},h:2}},ka:{}};z.q(J7,z.L);z.f=J7.prototype;z.f.ca=function(){return""};
z.f.ea=function(){return""};z.f.yW=z.h(436);z.f.ha=function(){return J7.prototype};z.f.fa={name:"PlacementsRequestQuery",ia:!1,fields:{requestContext:{name:"requestContext",g:function(){return z.hq},h:1},slots:{name:"slots",g:function(){return D7},ra:z.V,h:2},stateParams:{name:"stateParams",g:function(){return z.LM},h:3}},ka:{}};z.WW.prototype.uW=z.Y(598,function(a){a!=this.gQ&&this.Ab&&(this.Ab.ki.contentEditable=a);this.gQ=a});z.UF.prototype.kX=z.Y(589,function(a){this.Pn=a;return this});
z.ZF.prototype.kX=z.Y(588,function(a){this.Pn=a;return this});z.FF.prototype.j6=z.Y(587,function(a){a=K7(a);if(!a)return null;a=L7(a)&&L7(a).oo();return a?(a=a.gc())&&a.length?a[0].getName():null:null});I7.prototype.$r=z.Y(583,function(){return z.J(this,"placements")});
z.mD.prototype.$r=z.Y(582,function(a,b,c){var d=this;a=A6a(B6a(new J7,a),b);c&&a.yW(c);c=(new H7).Ck(a);var e=this.ma.la(z.aAa,{},c);return z.nD(this,e,function(){return z.u(d.pa.get(e,{background:!0}),function(a){a=d.Ka.kc(I7,a);d.Aa.sc(a);return a})})});z.fx.prototype.Vp=z.Y(498,function(){return z.J(this,"note")});z.gD.prototype.Vp=z.Y(497,function(a){return this.mc("Note",a)});z.Sr.prototype.ty=z.Y(471,function(){return z.J(this,"replyId")});
z.fx.prototype.ty=z.Y(470,function(){return z.J(this,"replyId")});z.Qr.prototype.lz=z.Y(469,function(a){return z.K(this,"highlight",a)});z.Qr.prototype.dU=z.Y(468,function(){return z.J(this,"highlight")});z.Qr.prototype.yv=z.Y(467,function(a){return z.K(this,"author",a)});z.Sr.prototype.yv=z.Y(466,function(a){return z.K(this,"author",a)});z.Qr.prototype.eK=z.Y(465,function(){return z.J(this,"author")});z.Sr.prototype.eK=z.Y(464,function(){return z.J(this,"author")});
z.Qr.prototype.bD=z.Y(463,function(){return z.J(this,"highlightId")});z.Qr.prototype.Aq=z.Y(462,function(a){return z.K(this,"state",a)});z.Sr.prototype.Aq=z.Y(461,function(a){return z.K(this,"state",a)});z.$w.prototype.Aq=z.Y(460,function(a){return z.K(this,"state",a)});z.Qr.prototype.Eg=z.Y(459,function(){return z.J(this,"noteId")});z.Sr.prototype.Eg=z.Y(458,function(){return z.J(this,"noteId")});z.fx.prototype.Eg=z.Y(457,function(){return z.J(this,"noteId")});
z.kr.prototype.zv=z.Y(456,function(a){return z.K(this,"authorId",a)});z.Qr.prototype.zv=z.Y(455,function(a){return z.K(this,"authorId",a)});z.Sr.prototype.zv=z.Y(454,function(a){return z.K(this,"authorId",a)});J7.prototype.yW=z.Y(436,function(a){return z.K(this,"stateParams",a)});I7.prototype.yW=z.Y(435,function(a){return z.K(this,"stateParams",a)});z.Hp.prototype.jf=z.Y(356,function(){return z.J(this,"catalogId")});z.eK.prototype.jf=z.Y(355,function(){return z.J(this,"catalogId")});
z.WJ.prototype.jf=z.Y(354,function(){return z.J(this,"catalogId")});z.UL.prototype.jf=z.Y(353,function(){return z.J(this,"catalogId")});z.CJ.prototype.jf=z.Y(352,function(){return z.J(this,"catalogId")});z.zL.prototype.jf=z.Y(351,function(){return z.J(this,"catalogId")});z.tK.prototype.jf=z.Y(350,function(){return z.J(this,"catalogId")});z.rL.prototype.jf=z.Y(349,function(){return z.J(this,"catalogId")});z.qL.prototype.jf=z.Y(348,function(){return z.J(this,"catalogId")});
z.pL.prototype.jf=z.Y(347,function(){return z.J(this,"catalogId")});z.kr.prototype.jf=z.Y(346,function(){return z.J(this,"catalogId")});z.fx.prototype.jf=z.Y(345,function(){return z.J(this,"catalogId")});z.AG.prototype.jf=z.Y(344,function(){return z.J(this,"catalogId")});z.yp.prototype.Dv=z.Y(316,function(a){return z.K(this,"location",a)});z.cq.prototype.Dv=z.Y(315,function(a){return z.K(this,"location",a)});D7.prototype.Dv=z.Y(314,function(a){return z.K(this,"location",a)});
E7.prototype.Dv=z.Y(313,function(a){return z.K(this,"location",a)});z.Vn.prototype.nU=z.Y(73,function(){return z.J(this,"point")});var O6a=/(?:https?:\/\/|www\.)\w[\w~#-@![\]]*/g;N7.prototype.nU=function(){var a=window.document.body;return z.Tf(a,this.ti.node)?this.ti:this.Yk&&z.Tf(a,this.Yk)?z.GM(this.PQ,this.Yk):this.Re&&(a=z.ks(this.gua,this.Re))?z.GM(this.PQ,a):null};z.q(P7,z.L);z.f=P7.prototype;z.f.ca=function(){return""};z.f.ea=function(){return""};z.f.ib=function(){return z.J(this,"content")};
z.f.jd=function(a){return z.K(this,"content",a)};z.f.Gb=function(){return z.J(this,"title")};z.f.Ic=function(a){return z.K(this,"title",a)};z.f.eK=function(){return z.J(this,"author")};z.f.yv=function(a){return z.K(this,"author",a)};z.f.getDate=function(){return z.J(this,"date")};z.f.setDate=function(a){return z.K(this,"date",a)};z.f.Lb=function(){return z.J(this,"collection")};z.f.setVersion=function(a){return z.K(this,"version",a)};z.f.kM=function(a){return z.K(this,"template",a)};
z.f.Rd=function(){return z.J(this,"subtitle")};z.f.xf=function(a){return z.K(this,"subtitle",a)};z.f.ha=function(){return P7.prototype};
z.f.fa={name:"TextshotInfo",ia:!1,fields:{content:{name:"content",g:z.W,h:1},altText:{name:"altText",g:z.W,h:2},title:{name:"title",g:z.W,h:3},author:{name:"author",g:z.W,h:4},date:{name:"date",g:z.W,h:5},authorAvatarId:{name:"authorAvatarId",g:z.W,h:6},collection:{name:"collection",g:z.W,h:7},collectionAvatarId:{name:"collectionAvatarId",g:z.W,h:8},collectionLogoId:{name:"collectionLogoId",g:z.W,h:9},collectionBackgroundColor:{name:"collectionBackgroundColor",g:z.W,h:10},collectionHighlightColor:{name:"collectionHighlightColor",
g:z.W,h:11},version:{name:"version",g:z.X,h:12},base64:{name:"base64",g:z.JG,h:13},template:{name:"template",g:z.W,h:14},mainStat:{name:"mainStat",g:z.W,h:15},mainStatTitle:{name:"mainStatTitle",g:z.W,h:16},subtitle:{name:"subtitle",g:z.W,h:17},icon:{name:"icon",g:z.W,h:18},imgKey:{name:"imgKey",g:z.W,h:19}},ka:{}};z.q(Q7,z.Tl);Q7.prototype.FL=function(){if(!this.qk)return null;var a=this.qk.nU();if(!a)return null;var b=this.xm.nU();return b?z.tm(a.node,a.offset,b.node,b.offset):null};var s8a={uUa:"quote-respond"};
z.q(S7,z.T);z.f=S7.prototype;z.f.Dk=function(){return this.Cm.Dk()};z.f.na=function(){S7.ya.na.call(this);z.Nw(this,this.V_,"data-redirect-type-quote",this.yxa,this);this.Ta(this.we,"click",this.Iw,this);z.ME(this.$a)&&z.Qv()&&this.Ta(this.we,"mouseover",this.Wua,this);this.$a.Za().Yr()&&!this.$a.Pb()&&z.v(this.ze.load(this.$a.Na()),z.Hw);var a=this.Dk();a&&(z.Nw(this,a,"quote",this.Tua,this),z.Nw(this,a,"quote-respond",this.Uua,this),z.Nw(this,a,"show",this.e4,this),z.Nw(this,a,"hide",this.Sxa,this))};
z.f.yxa=function(a){var b=z.BE(this.Cm,this.Dk().Fx);b&&(a.url=new z.td(this.ma.la(z.jDa,{postId:this.$a.Na()},{paragraphs:JSON.stringify([b.Ay.Kb().Vb()]),startOffset:b.start,endOffset:b.end})))};z.f.Iw=function(a){z.hs(a.target,function(a){if(a===this.we)return!0;var c=z.AB(a);if(3==c)return!0;if(7==c){if(c=a7a(this,a))if(T7(this,c),z.Qv())V7(this,c);else{var d=new z.pE;Z6a(this,c,a,d)}return!0}return!1}.bind(this))};
z.f.Wua=function(a){z.hs(a.target,function(a){if(a===this.we)return!0;var c=z.AB(a);if(3==c)return!0;if(7==c){c=z.$m();if(!(c&&!c.isCollapsed()||this.Dk()&&this.Dk().lq())&&(c=a7a(this,a))){var d=this.we.querySelector('.markup--quote[name~\x3d"'+c.ej()+'"]');a=new z.rE(a,100);Z6a(this,c,d,a);T7(this,c)}return!0}return!1}.bind(this))};
z.f.e4=function(){var a=z.$m();a&&!a.isCollapsed()&&T7(this,null);if(z.ME(this.$a)&&(a=z.BE(this.Cm,this.Dk().Fx))){var a=z.fwa(this.ze,a.Ay,a.start,a.end),b=this.Dk().Sa().querySelector(".js-highlightMenuQuoteButton");z.Oc(b,"is-active",!!a)}};z.f.Sxa=function(){this.Ip&&T7(this,null)};
z.f.Tua=function(){if(z.ME(this.$a)){var a=z.wE(this.Dk());if(a){var b=a.range,c=a.sJa,a=this.Dk().Sa().querySelector(".js-highlightMenuQuoteButton"),d=z.Hc(a,"is-active"),b=z.BE(this.Cm,b);z.v(z.u(this.ze.toggle(b.Ay,b.start,b.end,!c),function(a){z.AKa();d?z.yE(this.Dk()):V7(this,a);var b=c?"selection_menu":"quote_click_menu";W7(this,a.ej(),!d,b)},this),z.Hw)}}};
z.f.Uua=function(){if(z.ME(this.$a)&&z.Gl.supportsEdit){var a=z.wE(this.Dk());if(a){var b=z.BE(this.Cm,a.range);z.v(z.u(this.ze.create(b.Ay,b.start,b.end,1,!0),function(a){W7(this,a.ej(),!0,"selection_menu_quote_respond");this.za("quote-respond",a,b.Ay.name)},this),z.Hw)}}};
z.f.cva=function(a){var b=this.Ip,c=U7(this,b),d=b.Gd(),e=b.Ce(),b=a.query(".js-quoteAttributions-pileOn"),g=z.Hc(b,"is-active");z.v(z.u(this.ze.toggle(c,d,e,!0),function(b){var l=a.query(".js-quoteAttributions-pileOn");z.Pc(l,"is-active");if(l=z.nE(this.ze,c,d,e)){var p=Y6a(this,l),r=a.query(".js-quoteAttributions-info");z.P(r,N6a,p)}else a.Oc();!g&&z.Qv()&&(a.Oc(),V7(this,l));l=z.Qv()?"quote_hover":"quote_click_mobile";W7(this,b.ej(),!g,l)},this),z.Hw)};
z.f.dva=function(){if(z.ME(this.$a)&&z.Gl.supportsEdit){var a=U7(this,this.Ip),b=this.Ip.Gd(),c=this.Ip.Ce();z.v(z.u(this.ze.create(a,b,c,1,!0),function(b){W7(this,b.ej(),!0,"quote_respond");this.za("quote-respond",b,a.name)},this),z.Hw)}};z.f.eva=function(){var a=c7a(this,this.Ip);a&&z.uwa(this.Cm,a)};
z.f.Jfa=function(){var a=new Q7(this.we),b=this.ze.gu,c=Object.keys(b).concat(this.hca);z.Za(c);c.forEach(function(a){var c=b[a]||[],g=this.$a;if(g=(a=g.we&&z.ks(g.we,a))&&this.$a.cj(a))L6a(g,c),a.innerHTML=z.At(g,z.Gl,z.Awa(this.$a)),z.Tya(this.IAa,a)},this);this.hca=Object.keys(b);(a=a.restore())&&a.select()};z.q(X7,z.Lw);z.f=X7.prototype;
z.f.load=function(a){if(!z.Sp())return z.wc([]);this.pb=a;this.Lh||(this.Lh=z.v(z.u(this.wl.get(this.ma.la(z.bDa,{postId:a}),{background:!0}),this.GAa,this),z.Hw));return this.Lh.Wc()};z.f.gq=function(){return this.eca};z.f.dj=function(){return this.ffa};z.f.dU=function(a){return this.tda[a]||null};z.f.Vp=function(a,b){return z.qN(Y7(this,b),a)};z.f.lz=function(a,b){this.tda[a]=b};z.f.Na=function(){return this.pb};
z.f.GAa=function(a){var b=a.references.User;this.ffa=a.post.visibility;var c=a.value;if(c)for(var d=0;d<c.length;d++){var e=c[d];if("HIDDEN"!=e.state){var g=e.replies,k=b;if(g)for(var l=0;l<g.length;l++){var p=g[l],r=p.authorId||null;p.author=r&&k[r]||null}g=e.anchor;k=e.authorId||null;e.author=k&&b[k]||null;g=Y7(this,g);e=z.Rr(e);g.add(z.lC(this.Aa,e))}}if(a=a.highlights)for(b=0;b<a.length;b++)this.lz(a[b].id,z.Mn.Kb(z.Tr,a[b]));this.eca=!0};z.m(a8,z.T);a8.prototype.$r=function(a){var b=this;if(this.A2){var c=new z.hc;(0,window.setTimeout)(function(){return c.callback()},t8a);return q7a(c,function(){return b.$r(a)})}if(this.Mn[a])throw Error("Requesting multiple placements for the same location ("+a+") is not supported.");this.iZ.push((new D7).Dv(a).Rb(0));var d=new z.hc;this.Mn[a]=d;this.nw||(this.nw=(0,window.setTimeout)(this.FAa.bind(this),u8a));return d};
a8.prototype.FAa=function(){var a=this;this.A2=!0;z.pc(z.v(z.u(this.fb.$r(this.xBa,this.iZ,this.zga),function(b){var c=b.placements;b=b.stateParams;if(!c)return z.gb(a.Mn).forEach(function(a){return a.callback(null)});c.forEach(function(b){a.Mn[b.location].callback(b)});a.zga=b}),function(b){z.gb(a.Mn).forEach(function(a){return a.$g(b)})}),function(){var b=a.iZ;if(!z.la(b))for(var c=b.length-1;0<=c;c--)delete b[c];b.length=0;z.lb(a.Mn);(0,window.clearTimeout)(a.nw);a.nw=null;a.A2=!1})};
var t8a=20,u8a=500;z.m(b8,z.T);b8.prototype.na=function(){z.T.prototype.na.call(this);z.u(z.Pl(300),this.fsa,this)};
b8.prototype.fsa=function(){if(this.si&&this.si.postIds&&this.si.postIds.length){for(var a=this.ob(".js-meterThumbnail"),b=new z.hc,c=0;c<this.si.postIds.length;c++){var d=a[c],e=d.querySelector(".js-thumbnailImage"),g=z.Nv(z.vi,{imageId:this.si.previewImageIds[c]?this.si.previewImageIds[c]:"1*gqOHypRwp9HBuHaiSx6kWQ.png",strategy:"crop-fixed",width:40,height:40});z.mn(e,"background-image",'url("'+g+'"');z.u(b,this.aZ.bind(this,d,c==a.length-1))}b.callback()}};
b8.prototype.aZ=function(a,b){b=new z.rz(a,{name:b?"pulse-grow-50-110":"pulse-grow-50-105",duration:800+(b?200:0)});var c=z.u(new z.rz(a.querySelector(".js-thumbnailImage"),{name:"fade-in",duration:800}),function(){z.Ic(a,"is-read")}),d=new z.rz(a.querySelector(".js-thumbnailText"),{name:"color-light-to-white",duration:800});return new z.Hl([b.start(),c.start(),d.start()])};z.m(c8,z.T);c8.prototype.na=function(){z.T.prototype.na.call(this);var a=this.Oa.query(".js-postActionsBar");a&&(this.Va(a),(a=this.Oa.tx)?(z.Nw(this,a,"show",this.gC.bind(this,!0)),z.Nw(this,a,"dock",this.gC.bind(this,!0))):z.Nw(this,this.Db,"scroll-up",this.gC.bind(this,!0)),z.Nw(this,this.Db,"scroll-down",this.gC.bind(this,!1)),this.gC(!0),z.ns(this.Oa.query(".js-openInAppButton")),u7a(this),z.Pv()||this.Ta(this.Oa.oa(),"mousemove",z.Nl(200,this.mI,this)))};c8.prototype.Ca=function(){z.T.prototype.Ca.call(this)};
c8.prototype.mI=function(a){if(!this.yH){var b=z.IB(this.Bb);a.clientY>b.height-100&&this.gC(!0)}};c8.prototype.gC=function(a){if(this.$a.isPublished()&&!(this.yH===a||a&&t7a(this))&&(a||z.Sp()||t7a(this))){var b=this.Ga.$c(),c;b&&(c=b.se())&&z.bg(c,"js-postActionsBarContent")&&b.Oc();(this.yH=a)?this.za(v8a):this.za(w8a);z.Oc(this.oa(),"is-visible",this.yH)}};var v8a="show",w8a="hide";z.m(d8,z.T);z.f=d8.prototype;
z.f.na=function(){var a=this;z.T.prototype.na.call(this);this.wp&&(z.Nw(this,this.wp,v8a,function(){z.Ic(a.oa(),"is-abovePostActions");a.eQ=!0}),z.Nw(this,this.wp,w8a,function(){z.Mc(a.oa(),"is-abovePostActions");a.eQ=!1}));z.U(this.oa()).ba("dismiss-meter",this.wt,this).ba("expand-meter",this.aua,this);var b=this.si.postIds&&1<this.si.postIds.length,c=z.Jp().isMobile&&!z.Jp().isTablet;if(b||c)this.mw=(0,window.setTimeout)(this.wt.bind(this),x8a);z.u(z.Pl(300),this.gBa,this)};
z.f.Ca=function(){this.QB&&(this.QB.cancel(),this.QB=null);this.mw&&((0,window.clearTimeout)(this.mw),this.mw=null);z.T.prototype.Ca.call(this)};z.f.wt=function(){var a=this;this.QB=new z.rz(this.oa(),{name:this.eQ?z.Jp().isMobile?"pop-shift-down-35":"pop-shift-down-44":"pop-shift-down-0",duration:550,timing:"ease-in-out"});z.u(this.QB,function(){z.ms(a.oa());a.za(y8a)});this.QB.start()};
z.f.aua=function(){var a=this.query(z8a),b=this.query(A8a),c=this.query(B8a);z.ms(a);z.Ic(b,"is-visible");this.mw&&((0,window.clearTimeout)(this.mw),this.mw=null);z.P(c,Q6a);z.Mc(c,"u-xs-hide");z.kx(z.SGa,{unlockCount:this.si.postIds.length})};
z.f.gBa=function(){var a=this;this.Oa.oa().appendChild(this.oa());this.Yea=new z.rz(this.oa(),{name:this.eQ?z.Jp().isMobile?"pop-shift-up-35":"pop-shift-up-44":"pop-shift-up-0",duration:800,timing:"ease-in-out"});z.u(this.Yea.start(),function(){if(a.si&&a.si.postIds&&a.si.postIds.length){for(var b=a.ob(".js-meterThumbnail"),c=new z.hc,d=0;d<a.si.postIds.length;d++)z.u(c,a.aZ.bind(a,b[d],d==b.length-1));c.callback()}})};
z.f.aZ=function(a,b){b=new z.rz(a,{name:b?"pulse-grow-50-110":"pulse-grow-50-105",duration:800+(b?200:0)});var c=z.u(new z.rz(a.querySelector(".js-thumbnailImage"),{name:"fade-in",duration:800}),function(){z.Ic(a,"is-read")}),d=new z.rz(a.querySelector(".js-thumbnailText"),{name:"color-light-to-white",duration:800});return new z.Hl([b.start(),c.start(),d.start()])};var x8a=6E3,B8a=".js-dismissMeterIndicator",z8a=".js-expandMeterButton",A8a=".js-moreInfo",y8a="dismissed";z.m(e8,z.T);e8.prototype.na=function(){var a=this;z.T.prototype.na.call(this);return z.u(z.v(x7a(this),z.Hw),function(b){b=b.meteringInfo;var c=a.Oa.Da();a.wp=new c8(c,a.$a);if(b&&0<=b.postIds.indexOf(a.va.id)){var d=z.Ov(X6a,{post:a.va,meteringInfo:b});a.r2=new d8(c,d,a.wp,b);a.Oa.track(a.r2);z.Nw(a,a.r2,y8a,function(){!z.Sp()&&z.Gl.useragent.isMobile&&(K6a(a.Oa,a.wp)||a.Oa.track(a.wp))})}else(d=a.Oa.query(".js-paywall"))&&a.Oa.track(new b8(c,d,b));if(!w7a(a)||z.Sp())K6a(a.Oa,a.wp)||a.Oa.track(a.wp)})};z.m(f8,z.T);f8.prototype.na=function(){z.T.prototype.na.call(this);y7a(this)};z.m(g8,z.T);z.f=g8.prototype;z.f.na=function(){z.T.prototype.na.call(this);this.cI=this.T_();this.QR=z.DB(this.Bb,this.oa(),"fixed");z.Nw(this,this.Bb,"refresh",this.b$.bind(this));var a=this.oa();z.Jc(a,["u-fixed","u-transition--fadeOut300"]);z.mn(a,"transform","translateY("+this.b4+"px)");this.zJ();this.b$()};z.f.l9=function(a){this.cu=a;return this};z.f.b$=function(){this.i1();this.m1()};
z.f.i1=function(){this.zJ();var a=this.QR.fd(),a=a.top+a.height;if(z.IB(this.Bb).top+this.b4<=this.l_)return this.a4();if(a>=this.k_)return this.aB()};z.f.m1=function(){var a=this.QR.fd(),b=z.IB(this.Bb);return b.height<C8a||this.Fr>b.top||this.R0(a)?this.j0():this.eS()};z.f.R0=function(a){return(0,z.sc)(this.cI,function(b){return z.KN(a,b.fd())})};z.f.eS=function(){z.WR(this.oa(),"u-transition--fadeOut300","u-transition--fadeIn300")};z.f.j0=function(){z.WR(this.oa(),"u-transition--fadeIn300","u-transition--fadeOut300")};
z.f.aB=function(){var a=this.oa();z.WR(a,"u-fixed","u-absolute");z.mn(a,"transform","translateY("+this.l_+"px)")};z.f.a4=function(){var a=this.oa();z.WR(a,"u-absolute","u-fixed");z.mn(a,"transform","translateY("+this.b4+"px)")};z.f.zJ=function(){var a=z.DB(this.Bb,this.cu);this.k_=z.ZA(a)+a.We();this.l_=this.k_-this.QR.We()};z.f.T_=function(){var a=this;return z.lR(this.cu).map(function(b){return z.DB(a.Bb,b)})};var z7a=150,C8a=400;z.m(h8,z.T);z.f=h8.prototype;z.f.na=function(){z.T.prototype.na.call(this);this.rR=z.DB(this.Bb,this.oa());this.cI=this.T_();A7a(this)};z.f.l9=function(a){this.cu=a;return this};z.f.Zga=function(){if(0==this.rR.We())this.za(B8,!1,0,0);else{var a=this.oa(),b=B7a(this);this.Fr!=b&&((this.Fr=b)?(z.mn(this.oa(),"transform","translateY("+b+"px)"),a&&z.Mc(a,"u-invisible")):a&&z.Ic(a,"u-invisible"),this.za(B8,!z.Hc(a,"u-invisible"),b||0,this.rR.We()))}};
z.f.R0=function(a){return this.cI.some(function(b){return z.KN(a,b.fd())})};z.f.T_=function(){var a=this;return z.lR(this.cu).map(function(b){return z.DB(a.Bb,b)})};var B8="positioned";z.m(i8,z.T);i8.prototype.na=function(){z.T.prototype.na.call(this);this.eR=z.DB(this.Bb,this.l2);if(this.$a.isPublished()&&this.eR.We()>D8a){var a=z.Mw(this,".js-postShareWidget"),a=(new g8(this.qa)).Va(a).l9(this.l2);a.Fr=z.ZA(this.eR);this.gR=a;this.track(this.gR);z.Gl.variants.enable_related_reads_discovery&&(a=z.Mw(this,".js-sidebarRecirc"),this.t2=(new h8(this.qa)).Va(a).l9(this.l2),z.Nw(this,this.t2,B8,this.LEa.bind(this)),this.track(this.t2))}};
i8.prototype.LEa=function(a,b,c){this.gR.Fr=a?b+c:z.ZA(this.eR);this.gR.b$()};var D8a=300;j8.prototype.sT=function(a,b,c){return new S7(a,b,c)};j8.prototype.ds=function(){return s8a};C7a.prototype.get=function(a){return k8(this,a)};z.q(l8,z.WW);z.f=l8.prototype;z.f.YI=!1;z.f.nB="";z.f.ZI=0;z.f.ss=z.V;z.f.Eg=function(){return this.D1};z.f.save=function(){this.ib().length<=this.Bm&&this.yl()};z.f.Ib=function(){(0,window.clearTimeout)(this.ZI);l8.ya.Ib.call(this)};
z.f.na=function(){function a(a){a.stopPropagation()}l8.ya.na.call(this);this.nB=this.ib();this.jd(this.nB);this.Tx(13,this.I1,this);this.Tx(27,this.J1,this);this.Ab.Ta("blur",this.G1,!1,this);var b=this.Ab.Sa();z.aw(b,"keydown",a);z.aw(b,"keyup",a);z.aw(b,"keypress",a)};z.f.t8=function(a){return a};
z.f.yl=function(){if(this.isEnabled()){var a=this.ib().trim();if(a){this.uW(!1);var b=this.bja(),a=this.aja(a);this.za("saving",a);z.mc(z.v(z.u(this.wl.post(b,a.Vb()),this.sya,this),this.qya.bind(this,a)),this.uW.bind(this,!0))}}};z.f.sya=function(a){this.za("save",this.t8(a.value))};z.f.qya=function(a,b){this.za("fail",a);this.Ea.error(F7a());z.Hw(b)};z.f.I1=function(a){if(this.Ir&&z.yX(this.Ir))return!1;a.shiftKey||(a.preventDefault(),this.save());return!0};
z.f.J1=function(a){if(this.Ir&&z.yX(this.Ir))return!1;a.preventDefault();this.jd(this.nB);this.za("cancel");return!1};z.f.G1=function(){this.YI&&(this.ib().length>=this.Bm?(0,window.confirm)(this.fja())?(this.jd(this.nB),this.za("cancel")):this.focus():this.ZI=(0,window.setTimeout)(this.yl.bind(this),100))};z.q(m8,l8);z.f=m8.prototype;z.f.YY=null;z.f.zba=null;z.f.ZY=null;z.f.hk=null;z.f.p0=null;z.f.o0=null;z.f.sda=null;z.f.lz=function(a){this.hk=a;this.p0=a.startIndex;this.o0=a.endIndex;this.sda=a.content;return this};z.f.fja=function(){var a=z.n("Your note is too long; do you want to abandon your changes?");return(0,z.y)(""+a)};z.f.t8=function(a){var b=z.Lv();a=z.Rr(a).yv(b).zv(b.mb());this.hk&&a.bD()&&this.Af.lz(a.bD(),this.hk);var b=this.Af,c;c=z.lC(b.Aa,a);Y7(b,c.se()).add(c);return a};
z.f.bja=function(){return this.Eg()?this.ma.la(z.cDa,{postId:this.pb,noteId:this.Eg()}):this.ma.la(z.aDa,{postId:this.pb})};z.f.aja=function(a){var b=z.Lv();a=(new z.Qr({content:a,anchor:this.YY,anchorContent:this.zba,anchorImage:this.ZY?this.ZY.Vb():null,replies:[],createdAt:Date.now()})).yv(b);null!=this.p0&&null!=this.o0&&(b=new z.Tr({anchor:this.YY,startIndex:this.p0,endIndex:this.o0,content:this.sda}),a.lz(b));return a};z.q(n8,l8);n8.prototype.fja=function(){var a=z.n("Your reply is too long; do you want to abandon your changes?");return(0,z.y)(""+a)};n8.prototype.t8=function(a){var b=z.Lv();a=z.Mja(a).yv(b).zv(b.mb());z.J(this.Af.Vp(a.Eg(),this.Re),"replies").push(a);return a};n8.prototype.bja=function(){return this.Ffa?this.ma.la(z.fDa,{postId:this.pb,noteId:this.Eg(),replyId:this.Ffa}):this.ma.la(z.eDa,{postId:this.pb,noteId:this.Eg()})};
n8.prototype.aja=function(a){var b=z.Lv();return(new z.Sr({replyId:"",postId:this.pb,noteId:this.Eg(),content:a,createdAt:Date.now()})).yv(b)};z.q(p8,z.T);z.f=p8.prototype;
z.f.na=function(){p8.ya.na.call(this);z.U(this.oa()).ba("show-note-editor",this.w3,this).ba("hide-note-editor",this.l0.bind(this,!0)).ba("show-reply-editor",this.oDa,this).ba("hide-reply-editor",this.Ava,this).ba("save-note",this.ZBa,this).ba("save-reply",this.$Ba,this).ba("highlight-quote",this.Dva,this).ba("dismiss-note",this.lca.bind(this,!0),this).ba("delete-note",this.lca.bind(this,!1),this).ba("delete-reply",this.pta,this).ba("previous-highlight-tip",this.DAa,this).ba("next-highlight-tip",this.axa,
this);T7a(this);this.Dj&&F7(this.Dj)&&(S7a(this),z.Nw(this,F7(this.Dj),"add",this.pya,this));if(this.J2&&this.Fda&&this.Gda){var a=this.query(".js-inlineNewPostControl"),b=this.J2,c=this.$a.Na(),d=new z.SS(this.qa);d.aM("web-inline-quote-responses");d.Va(a);d.FG=!0;d.f_=!0;d.c_=!0;d.kM(P6a);d.mB=b;d.fM(c);z.TS(d,!0);this.Lc=d;this.Lc.ua();a=r8(this.DI);this.za("set-active-highlight",this.Re,a)}this.hk&&(this.w3(),this.Of&&this.Of.focus());s8(this,0)};
z.f.Ca=function(){this.gr&&this.gr.w5();(this.hk||this.DI)&&this.za("reset-highlight",this.Re,null);p8.ya.Ca.call(this)};z.f.Ib=function(){z.rx(this.oa());z.Ef(this.oa());z.Kl(this.Lc);z.Kl(this.Of);z.Kl(this.gr);z.Ll(z.gb(this.lk));this.gr=this.lk=this.Of=this.Lc=null;p8.ya.Ib.call(this)};z.f.vo=function(){if(this.Of&&this.Of.ib())return!0;for(var a=z.gb(this.lk),b=0;b<a.length;b++)if(a[b]&&a[b].ib())return!0;return this.Lc&&!this.Lc.isDismissable()?!0:!1};
z.f.Wq=function(){var a=[],b=[],c=[],d=this.rB&&(this.hk||this.DI);d||(this.Rw?(a=this.ze?G7(this.ze,this.Rw.quotes):[],b=this.Rw.notes,c=this.Rw.responses):(b=this.Af?z.QC(Y7(this.Af,this.Re)):[],this.D1||(this.ze?(a=this.ze,a=G7(a,a.gu[this.Re]||[])):a=[],c=this.Dj?M7(this.Dj,this.Re):[])));return z.Ov(P7a,{post:this.$a.Za(),quotes:a,notes:b,responses:c,i$:!!this.J2,EW:d,oM:this.rB,FE:this.Oga,jKa:z.LE(this.$a)})};
z.f.pya=function(){var a=this.query(".js-postList"),b=z.Ov(O7a,{responses:M7(this.Dj,this.Re)});z.Nf(b,a);S7a(this)};
z.f.w3=function(){if(this.rB){if(!this.Of){var a=this.query(".js-noteEditor"),b=z.Nv(M7a),a=this.Of=new m8(this.qa,a,this.$a.Na(),null,b),b=this.Re,c=this.$a.cj(this.pf.get(this.Re)),d=c.Ia(),c=4==c.type?c.De():null;a.YY=b;a.zba=d;a.ZY=c;(a=this.hk)&&this.Of.lz(a);z.Nw(this,this.Of,"saving",this.Xya,this);z.Nw(this,this.Of,"fail",this.Qxa,this);z.Nw(this,this.Of,"save",this.Sya,this)}z.Ic(this.query(".js-noteActions"),"is-noteEditorVisible");this.Of&&this.Of.focus()}};
z.f.ZBa=function(){this.Of&&this.Of.save()};z.f.Xya=function(a){this.Of.jd("");var b=this.query(".js-notesList");a={note:a,post:this.$a.Za(),EW:this.rB,oM:this.rB};a=z.Ov(o8,a);b.appendChild(a);z.Mc(b,"is-empty");T7a(this);this.l0()};z.f.Sya=function(a){var b=this.query(".js-notesList").lastChild;a=a.Eg();z.Ic(b,"js-note-"+a);b.setAttribute("data-note-id",a);(b=b.querySelector(".js-deleteNote"))&&b.setAttribute("data-action-value",a)};
z.f.Qxa=function(){var a=this.query(".js-notesList");a.removeChild(a.lastChild);z.Ic(a,"is-empty");this.w3()};z.f.l0=function(a){a?this.za("close"):this.Of&&(this.Of.ib()&&this.Of.jd(""),z.Mc(this.query(".js-noteActions"),"is-noteEditorVisible"))};z.f.oDa=function(a){(a=q8(a.target))&&this.rB&&U7a(this,a)};z.f.$Ba=function(a){a=q8(a.target);(a=this.lk[a])&&a.save()};
z.f.Yya=function(a){var b=a.Eg();this.lk[b]&&this.lk[b].jd("");var c=this.Af.Vp(b,this.Re).author.userId==a.author.userId,d=this.query(".js-note-"+a.Eg()+" .js-repliesList");a={note:a,post:this.$a.Za(),tka:c};a=z.Ov(o8,a);d.appendChild(a);z.Mc(d,"is-empty");V7a(this,b)};z.f.Tya=function(a){var b=this.query(".js-note-"+a.Eg()).querySelector(".js-repliesList").lastChild;a=a.ty();z.Ic(b,"js-reply-"+a);(b=b.querySelector(".js-deleteNote"))&&b.setAttribute("data-action-value",a)};
z.f.Rxa=function(a){var b=this.query(".js-note-"+a.Eg()+" .js-repliesList");b.removeChild(b.lastChild);z.Ic(b,"is-empty");U7a(this,a.Eg())};z.f.Ava=function(a){(a=q8(a.target))&&V7a(this,a)};z.f.Dva=function(a){a=a.target;var b=a.getAttribute("data-quote-creator-id"),c=k8(this.pf,this.Re);c&&(this.gr&&this.gr.w5(),this.gr=X7a(this,c,a,function(){W7a(this,b,!1);z.Kl(this.gr);this.gr=null}),W7a(this,b,!0))};
z.f.Cva=function(a){var b=k8(this.pf,this.Re);(a=this.Af.Vp(a.target.getAttribute("data-note-id"),this.Re))&&b&&(b=(b=a.bD())?this.Af.dU(b):null,this.za("set-active-highlight",this.Re,b))};z.f.Eva=function(a){var b=k8(this.pf,this.Re),c;c=this.Dj;a=a.target.getAttribute("data-post-id");c=F7(c)?z.qN(F7(c),a):null;b&&c&&(b=K7(c))&&(b=L7(b)&&L7(b).oo())&&(c=b.gc())&&c.length&&(b=r8(b),this.za("set-active-highlight",this.Re,b))};
z.f.c4=function(){var a=null;this.DI&&(a=r8(this.DI));this.hk&&(a=this.hk);this.za("reset-highlight",this.Re,a)};
z.f.lca=function(a,b){b=b.value;var c=this.Af.Vp(b,this.Re),d=this.query(".js-note-"+b);if(c&&d){z.ms(d);this.c4();this.ob(".js-note-item").every(function(a){return z.Hc(a,"u-hide")})&&this.l0(!0);var e=Z7(this.Af,c,"HIDDEN");z.v(e.Kl,function(b){this.xa.ua(a?G7a():H7a(),"error");e.JL();z.ns(d);(400>b.status||499<b.status)&&Z7(this.Af,c,"NEW")},this);z.u(this.xa.ua(a?J7a():K7a(),{type:"success",HE:!0}),function(){this.xa.Oc();e.JL();Z7(this.Af,c,"NEW");z.ns(d)},this)}};
z.f.pta=function(a){var b=a.value,c=this.query(".js-reply-"+b),d=q8(a.target);if(d&&c){z.ms(c);var e=$7(this.Af,b,d,this.$a.Na(),this.Re,"HIDDEN");z.v(e.Kl,function(){this.xa.ua(I7a(),"error");e.JL();z.ns(c);$7(this.Af,b,d,this.$a.Na(),this.Re,"")},this);z.u(this.xa.ua(L7a(),{type:"success",HE:!0}),function(){this.xa.Oc();e.JL();$7(this.Af,b,d,this.$a.Na(),this.Re,"");z.ns(c)},this)}};z.f.DAa=function(){s8(this,this.RP-1)};z.f.axa=function(){s8(this,this.RP+1)};z.q(t8,z.T);z.f=t8.prototype;z.f.na=function(){t8.ya.na.call(this);var a=[];z.LE(this.$a)&&a.push(this.Af.load(this.pb));this.Lda||(a.push(this.ze.load(this.pb)),a.push(this.Dj.load(this.pb)));this.ww=z.u(z.u(z.u(z.FR(a),function(){this.ww=null},this),this.render,this),this.lsa,this);z.Nw(this,this.Db,"resize-end",this.Zf,this)};z.f.Ca=function(){this.ww&&this.ww.cancel();t8.ya.Ca.call(this)};z.f.Ib=function(){this.ww=null;t8.ya.Ib.call(this)};
z.f.render=function(){D7a(this.pf,function(a,b){u8(this,b)},this)};z.f.Zf=function(){D7a(this.pf,function(a,b){d8a(this,b)},this)};z.f.lsa=function(){var a=this.ze.xp;z.Nw(this,a,"add",this.Oea,this);z.Nw(this,a,"remove",this.Oea,this);(a=F7(this.Dj))&&z.Nw(this,a,"add",this.Pya,this)};z.f.Oea=function(a){Y7a(this,Object.keys(z.jwa(this.ze,a instanceof Array?a:[a])))};z.f.Pya=function(a){Y7a(this,(a instanceof Array?a:[a]).map(this.Dj.j6,this.Dj))};
z.f.Wq=function(a){var b=window.document.createElement("div");b.className="notesMarkers";a.appendChild(b);return b};z.f.YH=function(a,b){z.pb(a,{startIndex:Math.min(a.startIndex,b.startIndex),endIndex:Math.max(a.endIndex,b.endIndex),notes:a.notes.concat(b.notes),quotes:a.quotes.concat(b.quotes),responses:a.responses.concat(b.responses)})};z.q(v8,z.T);z.f=v8.prototype;
z.f.na=function(){v8.ya.na.call(this);this.Ta(this.Oa.oa(),"click",this.Ewa,this,!0);z.U(this.WH).ba("select-anchor",this.dza,this);var a=this.$a.Za();if(a.Yr()&&!this.$a.Pb()){var b=z.Ap(a),b=2==a.visibility&&b&&!z.J(b.Qj(),"memberOfMembershipPlanId");a.allowResponses&&!b&&z.v(this.Dj.load(this.$a.Na(),"best"),z.Hw);z.v(this.ze.load(this.$a.Na()),z.Hw)}a.Qj().dK()&&(this.NQ=z.u(this.Af.load(this.$a.Na()),this.tya,this));this.d1&&x8(this,null);z.Nw(this,this.ub,"historyUpdate",function(){x8(this,
z.CE())},this);this.Ue&&z.Nw(this,this.Ue,"highlight",this.rya,this)};z.f.Ib=function(){z.Kl(this.Oh);this.Oh=null;z.Kl(this.qm);this.qm=null;this.WH&&z.U(this.WH).clear("select-anchor");this.NQ&&this.NQ.cancel();this.NQ=null;v8.ya.Ib.call(this)};z.f.qKa=function(a,b){w8(this,b,null,null,a)};z.f.rMa=function(){this.Oh&&this.Oh.Zf()};z.f.vo=function(){if(!this.qm)return!1;var a=this.qm.ib();return a?a.vo():!1};z.f.oya=function(a){a.subscribe("add",this.Yga,this);a.subscribe("remove",this.Yga,this)};
z.f.Yga=function(a){(z.la(a)?a:[a]).forEach(function(a){u8(this.Oh,a.se())},this)};z.f.tya=function(){var a=(0,z.Ea)();this.NQ=null;x8(this,z.CE());this.Ta(this.sm,z.eI,this.T1,this);z.ey(z.uFa,(0,z.Ea)()-a)};z.f.T1=function(a){(a=a.target.getAttribute("name"))&&k8(this.pf,a)&&d8a(this.Oh,a)};z.f.rya=function(){if(this.Ue){var a=j8a(this,this.Ue.Fx);z.yE(this.Ue);a&&(a=a.highlight,this.Vfa(a.anchor,a),w8(this,a.anchor,a))}};
z.f.Ewa=function(a){if(this.qm){var b=a.target;if(!z.Tf(this.qm.oa(),b)){var c=this.qm.ib(),d;if(!(d=!c)){a:if(c.Of&&c.Of.ib())c=!0;else{d=z.gb(c.lk);for(var e=0;e<d.length;e++)if(d[e]&&d[e].ib()){c=!0;break a}c=c.Lc&&!c.Lc.gj()?!0:!1}d=!c}d&&(c=this.qm&&this.qm.Un,d="select-anchor"==b.getAttribute("data-action"),this.R2(),c&&d&&z.Tf(c,b)&&a.stopPropagation())}}};
z.f.Pn=function(a){if(!z.Sv()){var b=a.Un,c=z.lw(b);a.Pl();a=a.oa();var d=z.lw(a),e=window.innerHeight,g=window.innerWidth,k=this.Oa.query(".js-metabar"),l=0;k&&(l=z.lw(k).height);d.height>=e-l?g7a(a):(z.hw(b),b=c.top+d.height>=e?z.iw().top+e-d.height-10:z.hw(b),c=z.lw(this.WH).left+10,c+d.width>=g&&(c=g-d.width-10),a.style.top=b+"px",a.style.left=c+"px")}};z.f.R2=function(){z.Kl(this.qm);this.qm=null};
z.f.dza=function(a){var b=z.hs(a.target,function(a){return z.Hc(a,"js-paragraphControl")},this.Zea),b=e8a(this.Oh,a.value,b);w8(this,a.value,null,null,null,b)};z.f.Vfa=function(a,b){if(this.$a.Pb()){var c=z.$m();this.RR=(c=c&&E7a(this.pf,c.Vf()))&&new Q7(c)}i8a(this,a,b)};z.f.FBa=function(a,b){i8a(this,a,b);this.$a.Pb()&&this.RR&&(a=this.RR.restore())&&a.select();this.RR=null};
z.f.sx=function(a){if(this.pf&&(a=k8(this.pf,a))){a=Math.max(z.hw(a),0);var b=z.py(this.Oa);this.rm&&this.rm.cancel();this.rm=new z.Hn(b,"scrollTop",600,a)}};k8a.prototype.sT=function(a,b,c){return new v8(a,b,c)};z.m(y8,z.T);z.f=y8.prototype;z.f.rc=function(a){this.va=a};z.f.kM=function(a){this.Sh=a};z.f.vLa=function(a){this.r3=a};z.f.wLa=function(a){this.iga=a};
z.f.na=function(){this.oa()?(z.T.prototype.na.call(this),z.U(this.oa()).ba("show-responses-stream-editor",this.pza,this).ba("show-other-responses",this.oga,this),z.P(this.oa(),this.Sh,{post:this.va}),this.va.Yr()&&z.v(z.u(z.u(z.u(J6a(this.fb,this.va.Cb(),"best"),this.Dfa.bind(this,"best")),this.mBa,this),function(){this.m4.D9&&this.oga()},this),z.Hw)):z.Hw("Attempted to initialize ResponsesStreamControl without root element.")};z.f.Ca=function(){z.U(this.oa()).clear("show-other-responses");z.T.prototype.Ca.call(this)};
z.f.Dfa=function(a,b){this.isActive()&&(b=b.Pe,"best"==a?(a=this.query(".js-responsesStream"),z.Nw(this,b,"add",this.oea.bind(this,b)),this.oea(b)):a=this.query(".js-responsesStreamOther"),b&&(z.Up()||0<b.Me())&&a&&(z.P(a,z.wP,{items:z.QC(b),context:2}),b=new z.uS(this.qa,b),b.Va(a),b.Dd(2),this.track(b),z.ns(this.query(".js-responsesStreamWrapper"))),this.iga&&(a=z.hw(a),z.ew(window.document.body,0,a)))};
z.f.mBa=function(){var a=this.query(".js-inlineNewPostControl"),b=this.query(".js-responsesLoggedOutPrompt");z.Up()?a?(this.Lc=z.TS(C6a((new z.SS(this.qa)).aM("web-inline-post-response").fM(this.va.Cb()),z.Mv(z.Eh,{post:this.va,mW:!0})),this.r3).Va(a),this.track(this.Lc)):b&&this.r3&&(a=z.gw(b),b=z.hw(b),z.ew(a,0,b)):b&&z.Ic(b,"u-hide")};
z.f.oga=function(){this.X1||(this.X1=z.mc(z.u(z.u(J6a(this.fb,this.va.Cb(),"other"),this.Dfa.bind(this,"other")),function(){z.ms(this.query(".js-showOtherResponses"));this.m4.D9=!0},this),function(){this.X1=null},this))};z.f.oea=function(a){(a=a.ql)&&a.next&&"other"==a.next.filter&&!this.m4.D9&&(z.ns(this.query(".js-responsesStreamWrapper")),z.ns(this.query(".js-showOtherResponses")))};z.f.hy=function(){this.Lc&&(z.rR(this.Lc.oa(),new z.fn(60,0,200,0)),this.Lc.hy())};
z.f.pza=function(){var a=this.query(".js-responsesStreamEditor"),b=this.query(".js-showResponsesStreamEditorButton");z.os(a)&&(z.ns(a),z.ms(b),this.hy())};z.q(z8,z.Lw);z8.prototype.focus=function(){this.isActive&&this.Cz.focus()};z8.prototype.close=function(){this.Cz&&!this.Cz.closed&&this.Cz.close();this.za("close");this.hg()};z8.prototype.isActive=function(){return this.Cz?!this.Cz.closed:!1};z8.prototype.Wa=function(){this.Cz=null;z8.ya.Wa.call(this)};z.f=m8a.prototype;z.f.pE=function(a,b,c){var d;d=z.Gl;var e=new z.Dh(z.Fl(d)),e=new z.td(e.Fl(a));d=R7(e,d);this.$w(d);z.kx(z.dF,{postId:a.id,type:b,source:c,dest:"facebook",dialogType:"native"})};z.f.w9=function(a){var b;b=z.Gl;var c=new z.Dh(z.Fl(b));a=new z.td(c.la(z.Bu,{catalogSlug:a.jf(),username:a.Ef().Hk()}));b=R7(a,b);this.$w(b)};z.f.x9=function(a){var b;b=z.Gl;var c=new z.Dh(z.Fl(b));a=new z.td(c.la(z.su,{sequenceSlug:a.vd()}));b=R7(a,b);this.$w(b)};
z.f.e6=function(){var a=this.ma.la(z.ICa);return this.pa.get(a)};z.f.$w=function(a){l8a(a,"facebook-share",{width:550,height:320})};z.q(A8,z.Il);
A8.prototype.open=function(a,b){this.va=a;this.Jx=b;this.Ea=this.zG.open({bodyHtml:z.Mv(l7a,this.Jx),type:"tweet"},!0);a=this.Ea.query(".js-tweetEditor-text");b=this.qa;var c=String,d;d=z.n("Enter tweet text.");d=(0,z.y)(""+d);this.wJ=new z.UX(b,a,c(d),!0);a=new z.pU(280,!0);a.$ba=O7;this.wJ.cb(a);a=T6a(h7a,this.Jx,z.Gl);this.wJ.jd(a);this.wJ.focus();o8a(this);z.U(this.Ea.cc).ba("remove-textshot",this.aga.bind(this,!1),this).ba("add-textshot",this.aga.bind(this,!0),this).ba("toggle-expand-image",this.gEa,
this);this.Ea.subscribe(z.Gy,this.UEa.bind(this))};A8.prototype.UEa=function(){var a=this.wJ.ib();if(p8a(this,a)){var b=this.WP?n8a(this):null;z.v(z.u(this.pa.post(this.ma.la(z.GCa),{tweet:a,textshotInfo:b}),function(a){a=z.Nv(j7a,{id:a.value});a=z.Mv(n7a,{kMa:a});this.xa.ua(a,{type:"success",Tk:1E4})},this),function(a){z.Hw(a);this.xa.ua(m7a(),"error")},this);z.Zx(z.jFa,{postId:this.va.id,type:this.Jx.shareType,source:this.Jx.zLa,dest:"twitter",style:this.WP?"textshot":null});this.Ea.close()}};
A8.prototype.aga=function(a){this.WP=a;z.Oc(this.Ea.query(".js-tweetEditor-imageContainer"),"u-hide",!a);z.Oc(this.Ea.query(".js-tweetEditor-addTextshot"),"u-hide",a)};A8.prototype.gEa=function(){var a=this.Ea.query(".js-tweetEditor-image");z.Pc(a,"tweetEditor-image--expanded")};z.f=q8a.prototype;z.f.yLa=function(a,b){var c=z.Rp(),d=a.creator||{},e=F6a(b),g=E6a(b),k=U6a(a,z.Gl);(b=p7a(b.g6()))&&z.Bd(k,b||"");var l={name:d.name||"",username:d.username||"",twitterScreenName:d.twitterScreenName||"",url:k.toString(),content:a.title,user:c,bMa:e,aMa:g,shareType:"highlight",zLa:"highlight_menu"};z.v(z.u(this.qa.load("tweet-dialog"),function(b){b.open(a,l)}),z.Hw);z.Zx(z.dF,{postId:a.id,type:"highlight",source:"highlight_menu",dest:"twitter",dialogType:"inapp"});return!0};
z.f.pE=function(a,b,c,d,e){var g=z.Rp().userId,k="highlight"==c?h7a:z.Sja,l=z.Gl,p=a.creator||{};b={content:b,name:p.name||"",username:p.username||"",twitterScreenName:p.twitterScreenName||"",Hha:p.userId==g,url:U6a(a,l).toString(),collaborators:d||[]};d=d&&d.length?String(k(b,null,l)):T6a(k,b,l);k=new z.td("https://twitter.com/intent/tweet");z.Jd(k,"text",d);this.$w(k);z.kx(z.dF,{postId:a.id,type:c,source:e,dest:"twitter",dialogType:"native"})};
z.f.w9=function(a){var b=z.Gl,c=new z.Dh(z.Fl(b)),c=(new z.td(c.la(z.Bu,{catalogSlug:a.jf(),username:a.Ef().Hk()}))).toString();a=z.C(""+z.ik(String(a.name))+((null==a.creator?null:a.creator.userId)!=b.currentUser.userId?" — "+z.Zr({twitterScreenName:null==a.creator?null:a.creator.twitterScreenName,name:null==a.creator?null:a.creator.name}):"")+" "+(""+c));b=new z.td("https://twitter.com/intent/tweet");z.Jd(b,"text",a);this.$w(b)};
z.f.x9=function(a){var b=new z.Dh(z.Fl(z.Gl)),b=(new z.td(b.la(z.su,{sequenceSlug:a.vd()}))).toString();a=z.C(""+z.ik(String(a.title))+" "+(""+b));b=new z.td("https://twitter.com/intent/tweet");z.Jd(b,"text",a);this.$w(b)};z.f.$w=function(a){l8a(a,"twitter-share",{width:670,height:420})};var E8a=z.Hx,F8a=E8a.Da();z.Kx(z.Kx(z.Kx(z.Kx(z.Kx(F8a.scope("screen").add("quotes",j8).add("quote-responses",k8a).add("responses-stream-control",y8).add("notes-data",X7),"PlacementsStore",a8),"Meter",e8),"PostMeterBar",d8),"PostFooterReadNext",f8),"PostSidebar",i8);F8a.scope("app").add("twitter",q8a).add("facebook",m8a).add("tweet-dialog",A8);z.rN(E8a,"notes");}).call(this, _mdm);
